<?php
    $objectManager  = \Magento\Framework\App\ObjectManager::getInstance();        
    $storeManager   = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $store          = $storeManager->getStore();
    $baseurl        = $store->getBaseUrl();
?>
<?php $defaultInformation = $this->helper('Magestore\OneStepCheckout\Helper\Config')->getDefaultAddressInformation();?>
<script type='text/javascript'>
    require([
        'Magestore_OneStepCheckout/js/model/addressFieldManager'
    ], function(addressFieldManager) {
        addressFieldManager.init(<?php echo $this->helper('Magestore\OneStepCheckout\Helper\Config')->getAddressFieldsJsonConfig();?>);
    })
</script>
<ol class="one-step-checkout onestepcheckout-index-index three-columns-new-osc clearfix">
    <li id="checkout" data-bind="scope:'checkout'" class="checkout-container">
        <div id="checkout-loader" data-role="checkout-loader" class="loading-mask show" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                     alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#checkout": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
            window.giftOptionsConfig = <?php echo $block->getLayout()->createBlock('Magento\GiftMessage\Block\Cart\GiftOptions')->getGiftOptionsConfigJson(); ?>;
            // Create aliases for customer.js model from customer module
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            window.customerData = window.checkoutConfig.customerData;

            window.checkoutConfig.defaultCountryId = '<?php /* @escapeNotVerified */ echo $defaultInformation['country_id']; ?>';
            window.checkoutConfig.defaultPostcode = '<?php /* @escapeNotVerified */ echo $defaultInformation['postcode']; ?>';
            window.checkoutConfig.defaultRegionId = '<?php /* @escapeNotVerified */ echo $defaultInformation['region_id']; ?>';
            window.checkoutConfig.defaultCity = '<?php /* @escapeNotVerified */ echo $defaultInformation['city']; ?>';
        </script>

        <script>
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
                return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
            })
        </script>

    </li>
</ol>

 <script>
 require([ 'jquery', 'jquery/ui'], function($){
 
 $(document).ready(function(){
  // put your code here if you want it in document.ready 
  //AGTW1O3
  //alert('gdfgfdgfdgfg');
 // zipcode-val
 
// alert('test');
 
 function test(fg)
 {
 alert('test');
 }
 
  $("#zipcode-val").each(function(){
   alert($(this).val())
   });
	
	
  var title = $("input").attr("name","postcode"); 
  
 // alert(title);
  
  
  $.each($('input[type=text]'),function(){
 // alert($(this).attr("name"));
  
 // alert($(this).attr("id"));
  
});

  
   //  $("#divid").text(title);
 
  });

 setTimeout(function(){

$(window).load(function(){

//  alert('test');
 
 
 var title = $("input").attr("name");


 function test()
 {
 alert('test');
 }
 
 /*   $("#AGTW1O3").trigger('keyup');
   $("#AGTW1O3").hide();
   $("#AGTW1O3").trigger('keyup');
   alert("hiwq"); */

   });

 }, 2000);

});
 
 </script>
