<?php
      $objectManager   = \Magento\Framework\App\ObjectManager::getInstance();
      $category        = $objectManager->get('Magento\Framework\Registry')->registry('kb_current_category');
      $catColl         = $objectManager->get('Mirasvit\Kb\Model\Category');
      $resource        = $objectManager->get('Magento\Framework\App\ResourceConnection');
      $connection      = $resource->getConnection(); 
      $storeManager1   = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
      $currentStore    = $storeManager1->getStore();
      $mediaUrl        = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
      $nn=$mediaUrl."kb";
      $likeblock = $objectManager->create('Nuluv\Liker\Block\Liker');
      $page_type = 3; //For knowledge hub page 
	  
	  
	  
if(isset($_GET['month']) || isset($_GET['parenting']) || isset($_GET['pregnant'])) 
{
	$month = isset($_GET['month'])?" and mstart.pregnant_month='".$_GET['month']."'":'';
			
	$parenting = isset($_GET['parenting'])?" and mstart.parenting='".$_GET['parenting']."'":'';

	$pregnant = isset($_GET['pregnant'])?" and mstart.getting_pregnant='".$_GET['pregnant']."'":'';
	
	if($_GET['sort']=='popular')
	{
		//$sql = "SELECT mstcat.name catname, mstart.created_at created_at, mstart.url_key url, mstart.image image, mstart.name as name, liker_liker.* FROM mst_kb_category as mstcat INNER JOIN mst_kb_article_category as mstartcat ON mstartcat.ac_category_id = mstcat.category_id INNER JOIN mst_kb_article as mstart ON mstartcat.ac_article_id = mstart.article_id left join liker_liker on mstart.article_id=liker_liker.product_id where liker_liker.page_type=3 $month $parenting $pregnant order by liker_liker.likes desc";
		$sql = "SELECT mstcat.name catname, mstart.created_at created_at, mstart.url_key url, mstart.article_id article_id, mstart.image image, mstart.name as name, liker_liker_view.* FROM mst_kb_category as mstcat INNER JOIN mst_kb_article_category as mstartcat ON mstartcat.ac_category_id = mstcat.category_id INNER JOIN mst_kb_article as mstart ON mstartcat.ac_article_id = mstart.article_id left join liker_liker_view on mstart.article_id=liker_liker_view.product_id where 1=1 $month $parenting $pregnant order by liker_liker_view.likes desc";
		
	} else {
		
		$sort = $_GET['sort']?" order by mstart.name ".$_GET['sort']:'';
		
		$sql = "SELECT mstcat.name catname, mstart.created_at created_at, mstart.url_key url, mstart.article_id article_id, mstart.image image, mstart.name as name FROM mst_kb_category as mstcat INNER JOIN mst_kb_article_category as mstartcat ON mstartcat.ac_category_id = mstcat.category_id INNER JOIN mst_kb_article as mstart ON mstartcat.ac_article_id = mstart.article_id where 1=1 $month $parenting $pregnant $sort";
	}


	$result = $connection->fetchAll($sql);
	
	$searchBy = '';
    if(count($result) > 0){ 
	$searchBy .= isset($_GET['month'])?$_GET['month'].' ':'';
	$searchBy .= isset($_GET['parenting'])?$_GET['parenting'].' ':'';
	$searchBy .= isset($_GET['pregnant'])?$_GET['pregnant']:'';
	?>
		<div class="search-result-for"><cite>Search Result For '<?=$searchBy ?>'</cite></div>
		<div id="filter-tab-1" class="tab-content current">          
			<ul class="hub_list">

				<?php
				foreach ($result as $article) 
				{
					$publish_datte  = $article['created_at'];
					$tempDate       = $publish_datte;
					$day            = date('l', strtotime($tempDate));
					$month          = date('F jS Y ',strtotime($tempDate)); 
					$postId         =$article['article_id'];
          
					$total_likes =$likeblock->getLikeCount($postId);
					$client_like_count =$likeblock->isLikeAlredySubmitted($postId);
					if($client_like_count){
					  $value='Unlike';
					  $type_id=0;
					  $class='liked';
					}else{
					  $value='Like';
					  $type_id=1;
					  $class='';
					}

        ?>
					<li>
						<div class="hub-box">
							<a href="<?=$article['url'] ?>">
								<div class="hub-box-image">
									<img src="<?php if(!empty($article['image'])){ echo $nn.'/'.$article['image'];} else { echo $this->getViewFileUrl('images/hub_cat_01.jpg');} ?>"/>
								</div>
							</a>
							<div class="hub-details">
								<div class="hub_flex">
									<span class="hub_type"><?php echo $article['catname'] ?></span>
									<div class="hub_title">
										<a href="<?php echo $article['url']; ?>"><?php echo $article['name']; ?></a>
									</div>
								</div>
							</div>
							<div class="box-bottom">
								<div class="pull-left"><?php echo $month; ?></div>
								<!-- <div class="pull-right"><i class="fa fa-heart"></i><?php //echo $article->getRating(); ?></div> -->
                <div class="like-action pull-right">

        <button value="<?php echo  $value;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $postId; ?>" class="like <?php echo $class;?>">
    </button>
    (<span id="likes_<?php echo $postId; ?>"><?php echo $total_likes; ?></span>)
   <img class="like-loader" id="like-loader-<?php echo $postId?>" style="display:none" src="<?php echo $mediaUrl.'loader.gif'?>">

    </div>
								<div class="clearfix"></div>
							</div>
						</div>
					</li>
			<?php } ?>
			</ul>
		</div>
		
	<?php } else { echo "There is no article matching collections."; } 
	} elseif ($category->getCategoryId() == 2 || $category->getCategoryId() == 9) 
     {
      $articles4 = $objectManager->get('Mirasvit\Kb\Model\ResourceModel\Article\Collection')->load();
      
       ?>
        <div id="filter-tab-1" class="tab-content current sdsdsds">          
              <ul class="hub_list">
                <?php 
                foreach ($articles4 as $article_1)
                {


                  $publish_datte  = $article_1['created_at'];
                  $tempDate       = $publish_datte;
                  $day            = date('l', strtotime($tempDate));
                  $month          = date('F jS Y ',strtotime($tempDate));
                  $postId         =$article_1['article_id'];

                  $sql_5      = "SELECT mstcat.* FROM mst_kb_category as mstcat
                  INNER JOIN mst_kb_article_category as mstartcat ON mstartcat.ac_category_id = mstcat.category_id
                  INNER JOIN mst_kb_article as mstart ON mstartcat.ac_article_id = mstart.article_id where mstart.article_id=".$article_1->getArticleId()."";
                  $result5    = $connection->fetchAll($sql_5);
                ?>

                <?php
        $total_likes =$likeblock->getLikeCount($postId);
        $client_like_count =$likeblock->isLikeAlredySubmitted($postId);
        if($client_like_count){
          $value='Unlike';
          $type_id=0;
          $class='liked';
        }else{
          $value='Like';
          $type_id=1;
          $class='';
        }

        ?>
                <li>
                  <div class="hub-box fff">
                      <a href="<?= $article_1->getUrl(); ?>"><div class="hub-box-image" ><img src="<?php if(!empty($article_1['image'])){ echo $nn.'/'.$article_1['image'];} else { echo $this->getViewFileUrl('images/hub_cat_01.jpg');} ?>"/></div></a>  
                      <div class="hub-details">
                          <div class="hub_flex">
                            <span class="hub_type"><?php echo $result5[0]['name'] ?></span>
                            <div class="hub_title"><a href="<?= $article_1->getUrl(); ?>"><?php echo $article_1->getName(); ?></a></div>
                          </div>
                      </div>
                      <div class="box-bottom">
                          <div class="pull-left"><?php echo $month; ?></div>
                            <div class="like-action pull-right">

        <button value="<?php echo  $value;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $postId; ?>" class="like <?php echo $class;?>">
    </button>
    (<span id="likes_<?php echo $postId; ?>"><?php echo $total_likes; ?></span>)
   <img class="like-loader" id="like-loader-<?php echo $postId?>" style="display:none" src="<?php echo $mediaUrl.'loader.gif'?>">

    </div>
                          <div class="clearfix"></div>
                        </div>
                    </div>
                </li>  
              <?php } ?>
             </ul> 
          </div>
          <div>
            <?php if ($block->getPagerHtml()): ?>
                    <?php echo $block->getPagerHtml(); ?>
              <?php endif ?>
          </div>
      <?php } else {
                
                $sql        = "Select * FROM mst_kb_article_category WHERE ac_category_id='".$category->getCategoryId()."'";
                $result1    = $connection->fetchAll($sql);
                $sql_1      = "Select * FROM mst_kb_category WHERE category_id='".$category->getCategoryId()."'";
                $result_1   = $connection->fetchAll($sql_1);
                $result2    = array();     
                foreach ($result1 as $value) 
                {
                  $ac_article_id = $value['ac_article_id'];
                  $sql2          = "Select * FROM mst_kb_article WHERE article_id='".$ac_article_id."'"; 
                  $result2       = $connection->fetchAll($sql2);
                  $publish_datte = $result2[0]['created_at'];
                  $tempDate      = $publish_datte;
                  $day           = date('l', strtotime($tempDate));
                  $month         = date('jS F Y',strtotime($tempDate));
                  $model = $objectManager->get('Mirasvit\Kb\Model\Article')->load($ac_article_id);
            ?>
            <div id="filter-tab-1" class="tab-content current hhhhhhhhhhhh">          
              <ul class="hub_list">
                <li>
                  <div class="hub-box kkk">
                      <a href="<?php echo $model->getUrl();?>"><div class="hub-box-image" ><img src="<?php if(!empty($result2[0]['image'])){ echo $nn.'/'.$result2[0]['image'];} else { echo $this->getViewFileUrl('images/hub_cat_01.jpg');} ?>"/></div></a>
                      <div class="hub-details">
                          <div class="hub_flex">
                            <span class="hub_type"><?php echo $result_1[0]['name'] ?></span>
                            <div class="hub_title"><a href="<?php echo $model->getUrl();?>"><?=$result2['0']['name'];?></a></div>
                          </div>
                      </div>
                      <div class="box-bottom">
                          <div class="pull-left"><?= $month; ?></div>
                            <div class="pull-right hubrate"><span><i class="fa fa-heart"></i></span><span><?php echo  $model->getRating();?></span></div>
                          <div class="clearfix"></div>
                        </div>
                    </div>
                </li>
              </ul>
            </div>   
    <?php }  }  ?> 
   