<?php
/** @var \Mirasvit\Kb\Block\Category\Sidebar $block */

$tree = $block->getCategoryTree();
$currentCat = $block->getCurrentCatId();
$minLevel = $block->getMinCategoryLevel();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseurl=$store->getBaseUrl();
$KnowledgehubUrl=$baseurl.'knowledge-hub.html';
$atozurl= $baseurl.'knowledge-hub/health-a-z.html';

$request     = $objectManager->get('\Magento\Framework\App\Request\Http');
 $action_name = $request->getActionName();
 $module_name = $request->getModuleName();
 $controller_name = $request->getControllerName();

$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();
$curUrl = explode("?", $currentUrl);

$current = rtrim($curUrl[0],'/');

$param = $block->getRequest()->getParam('article');


$articles4 = $objectManager->get('Mirasvit\Kb\Model\ResourceModel\Article\Collection')->load();

$storeManager1   = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
      $currentStore    = $storeManager1->getStore();
      $mediaUrl        = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
      $nn=$mediaUrl."kb";
?>
<?php if (count($tree) > 0): ?>
    <div class="block block-collapsible-nav kb__category-sidebar">
        <!-- <div class="title block-collapsible-nav-title"
             data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-kb", "selectorsToggleClass": "active"}}'>
            <strong><?//= __('Categories') ?></strong>
        </div> -->
        <div class="product-filter filter"  id="block-collapsible-nav-kb">
            <ul class="nav items">
                <?php $p = 1; foreach ($tree as $category): ?>
                    <li class="item level-<?= $category->getLevel() - $minLevel + 1 ?>">
                        <a class="tab-link <?php if ($current==$KnowledgehubUrl && $p == 1) {echo "current";} elseif ($current == $category->getUrl()) {echo "current";} ?>" href="<?= $category->getUrl() ?>"><?= $category->getName() ?>
                            <!-- <span class="count"><?//= $category->getArticlesNumber($block->getStoreId()) ?></span> -->
                        </a>
                    </li>
                <?php $p++; endforeach ?>
            </ul>
        </div>
    </div>
	<?php
	if(strpos($current, 'health-a-z') || $currentCat==2){  ?>
    <div class="alpha_pagination">
		<?php foreach (range('A', 'Z') as $i){ ?>
			<a href="<?php echo $block->getUrl('kbase/category/filter');?>article/<?=$i?>" style="<?php if ($param==$i) { echo "filterColor";} ?>"><?=$i?></a>
		<?php }?>

<?php if ($action_name=='view' && $module_name=='kbase' ) { ?>
      <div class="kb__search-box hub_search">
    <div class="search-title">Expert advices for parenting and more!</div>
    <form action="<?= $block->getUrl('kbase/article/s')?>" method="GET" id="kb-s-form" class="abc">
        <input id="mpblog-search-box" name='s' id='s' type="text" placeholder="Search..." class="form-control input-text required-entry" required value="<?= $block->getQuery() ?>">
        <button class="action primary" title="Submit" type="submit">
            <span><i class="fa fa-fw fa-search"></i></span>
        </button>
    </form>
</div>  
<?php } elseif ($action_name=='filter' && $module_name=='kbase') { ?>
<form action="<?= $block->getUrl('kbase/article/s')?>" method="GET" id="kb-s-form">
        <input name='s' id='s' type="text" placeholder="Search..." class="form-control input-text required-entry" required value="<?= $block->getQuery() ?>">
    </form>
<?php } ?>

</div>
	<?php } ?>
	<?php endif ?>
	
	
	<?php
		$artarr=array();
		$months = array();
		$pregnant = array();
		$parenting = array();
		foreach ($articles4 as $article_1){
			$months[] = $article_1->getPregnantMonth();
			$pregnant[] = $article_1->getGettingPregnant();
			$parenting[] = $article_1->getParenting();
			$url=str_replace('.htm','.html',$article_1->getUrl());
			if(!empty($article_1['image'])){ $imghtml=$nn.'/'.$article_1['image'];} else { $imghtml=$this->getViewFileUrl('images/hub_cat_01.jpg');}
			$artarr[]=array('value'=>$article_1->getName(),'url'=>$url,'image'=>$imghtml,'desc'=>$article_1->getName());			
		}
	 ?>
	
	<div class="kbmain-cls">
		<ul class="kbmain-inner-cls">
			<li>
				<select name="month" id="months" onchange="monthVal(this.value)">
					<option value="">Month</option>
					<?php 
					$months = array_unique($months);
					sort($months);
					foreach ($months as $month){ ?>
						<option value="<?=$month ?>" <?php if(isset($_GET['month'])){ echo ($_GET['month']==$month?'selected':''); } ?>><?=$month ?></option>
					<?php } ?>
				</select>
				<select name="pregnant" id="pregnants" onchange="pregnantVal(this.value)">
					<option value="">Getting Pregnant</option>
					<?php 
					$pregnants = array_unique($pregnant);
					sort($pregnants);
					foreach ($pregnants as $pregnant){ ?>
						<option value="<?=$pregnant ?>" <?php if(isset($_GET['pregnant'])){ echo ($_GET['pregnant']==$pregnant?'selected':''); } ?>><?=$pregnant ?></option>
					<?php } ?>
				</select>
				<select name="parenting" id="parentings" onchange="parentingVal(this.value)">
					<option value="">Parenting</option>
					<?php 
					$parentings = array_unique($parenting);
					sort($parentings);
					foreach ($parentings as $parenting){ ?>
						<option value="<?=$parenting ?>" <?php if(isset($_GET['parenting'])){ echo ($_GET['parenting']==$parenting?'selected':''); } ?>><?=$parenting ?></option>
					<?php } ?>
				</select>
			</li>			
		</ul>
		<div class="toolbar toolbar-products" style="display: block;">
			<div class="orderby">
				<span>Order By</span>
				<select style="width:70%;" id="sorter" class="custom_select" onchange="articleListSorting(this.value);" name="sorterone">
					<option value="asc" <?php if(isset($_GET['sort'])){ echo $_GET['sort']=='asc'?'selected':''; } ?>>Relevance</option>
					<option value="asc" <?php if(isset($_GET['sort'])){ echo $_GET['sort']=='asc'?'selected':''; } ?>>Alphabetically, A-Z</option>
					<option value="desc" <?php if(isset($_GET['sort'])){ echo $_GET['sort']=='desc'?'selected':''; } ?>>Alphabetically, Z-A</option>
					<option value="popular" <?php if(isset($_GET['sort'])){ echo $_GET['sort']=='popular'?'selected':''; } ?>>Popular</option>
				</select>
			</div>
		</div>
	</div>

<style type="text/css">
.filterColor{
	    border-bottom: 3px solid #7e6674 !important;
	    background-color: #FF9FAA !important;
	}
	
.kbase-category-filter .product-filter{
	margin: auto;
    width: 33%;
    margin-left:475px;
}
</style>

<script>	

		function articleListSorting(sortVal)
		{
			var curUrl = '<?php echo $current ?>';
			
			var preg = jQuery('#pregnants').val();
			
			var parenting = jQuery('#parentings').val();
			
			var month = jQuery('#months').val();
			
			month = month==''?'?':'?month=' + month + '&';
			
			preg = preg==''?'':'pregnant=' + preg + '&';
			
			parenting = parenting==''?'':'parenting=' + parenting + '&';
			
			var filterUrl = curUrl + month + preg + parenting + 'sort=' + sortVal;
			
			window.location.href = filterUrl;
		}

		function monthVal(month)
		{
			var curUrl = '<?php echo $current ?>';
			
			var preg = jQuery('#pregnants').val();
			
			var parenting = jQuery('#parentings').val();
			
			var sortVal = jQuery('#sorter').val();
			
			month = month==''?'?':'?month=' + month + '&';
			
			preg = preg==''?'':'pregnant=' + preg + '&';
			
			parenting = parenting==''?'':'parenting=' + parenting + '&';
			
			var filterUrl = curUrl + month + preg + parenting + 'sort=' + sortVal;
			
			window.location.href = filterUrl;
		}
		
		function pregnantVal(preg)
		{
			var curUrl = '<?php echo $current ?>';
			
			var month = jQuery('#months').val();
			
			var parenting = jQuery('#parentings').val();
			
			var sortVal = jQuery('#sorter').val();
			
			month = month==''?'?':'?month=' + month + '&';
			
			preg = preg==''?'':'pregnant=' + preg + '&';
			
			parenting = parenting==''?'':'parenting=' + parenting + '&';
			
			var filterUrl = curUrl + month + preg + parenting + 'sort=' + sortVal;
			
			window.location.href = filterUrl;
		}
		
		function parentingVal(parenting)
		{
			var curUrl = '<?php echo $current ?>';
			
			var preg = jQuery('#pregnants').val();
			
			var month = jQuery('#months').val();
			
			var sortVal = jQuery('#sorter').val();
			
			month = month==''?'?':'?month=' + month + '&';
			
			preg = preg==''?'':'pregnant=' + preg + '&';
			
			parenting = parenting==''?'':'parenting=' + parenting + '&';
			
			var filterUrl = curUrl + month + preg + parenting + 'sort=' + sortVal;
			
			window.location.href = filterUrl;
		}
	
        require([
            'jquery',
            'autocomplete'
            ], function ($) {
                $("#blog-section-search").click(function () { 
                    $("#blog-section-input").show();
                });
                $("#close-serach").click(function () { 
                    $("#blog-section-input").hide();
                });
                var visibleImage = 1;
                $('#mpblog-search-box').autocomplete({
                    lookup: <?php echo json_encode($artarr); ?>,
                    lookupLimit: 10,
                    maxHeight: 2000,
                    minChars: 1,
                    onSelect: function (suggestion) {
                        var urlString = suggestion.url;
                        window.location.href = urlString.substring(0,urlString.length - 1);
                    },
                    formatResult: function (suggestion, currentValue) {
                        var urlString = suggestion.url;
                        var html = "<a class='mpblog-suggestion' href='" + urlString.substring(0,urlString.length - 1) + "'>";
                        if (visibleImage) {
                            html += "<div class='mpblog-suggestion-left'><img class='img-responsive' src='" + suggestion.image + "' /></div>"
                        }
                        html += "<div class='mpblog-suggestion-right'>" +
                        "<div class='mpblog-product-line mpblog-product-name'>" + suggestion.value + "</div>" +
                        "<div class='mpblog-product-des'><p class='mpblog-short-des'>" + suggestion.desc + "</p></div></div></a>";

                        return html;
                    }
                });
            });
        </script>