<?php
/** @var \Mirasvit\Kb\Block\Category\Sidebar $block */

$tree = $block->getCategoryTree();
$minLevel = $block->getMinCategoryLevel();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseurl=$store->getBaseUrl();
$KnowledgehubUrl=$baseurl.'knowledge-hub.html';
$atozurl= $baseurl.'knowledge-hub/health-a-z.html';

$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');
$current = $urlInterface->getCurrentUrl();


?>
<?php if (count($tree) > 0): ?>
    <div class="block block-collapsible-nav kb__category-sidebar">
        <!-- <div class="title block-collapsible-nav-title"
             data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-kb", "selectorsToggleClass": "active"}}'>
            <strong><?//= __('Categories') ?></strong>
        </div> -->
        <div class="product-filter filter"  id="block-collapsible-nav-kb">
            <ul class="nav items">
                <?php $p = 1; foreach ($tree as $category): ?>
                    <li class="item level-<?= $category->getLevel() - $minLevel + 1 ?>">
                        <a class="tab-link <?php if ($current==$KnowledgehubUrl && $p == 1) {echo "current";} elseif ($current == $category->getUrl()) {echo "current";} ?>" href="<?= $category->getUrl() ?>"><?= $category->getName() ?>
                            <!-- <span class="count"><?//= $category->getArticlesNumber($block->getStoreId()) ?></span> -->
                        </a>
                    </li>
                <?php $p++; endforeach ?>
            </ul>
        </div>
    </div>
    <div class="alpha_pagination">
        <a href="#">A</a>
        <a href="#">B</a>
        <a href="#">C</a>
        <a href="#">D</a>
        <a href="#">E</a>
        <a href="#">F</a>
        <a href="#">G</a>
        <a href="#">H</a>
        <a href="#">I</a>
        <a href="#">J</a>
        <a href="#">K</a>
        <a href="#">L</a>
        <a href="#">M</a>
        <a href="#">N</a>
        <a href="#">O</a>
        <a href="#">P</a>
        <a href="#">Q</a>
        <a href="#">R</a>
        <a href="#">S</a>
        <a href="#">T</a>
        <a href="#">U</a>
        <a href="#">V</a>
        <a href="#">W</a>
        <a href="#">X</a>
        <a href="#">Y</a>
        <a href="#">Z</a>
      </div>
<?php endif ?>

<div class="kb__search-box hub_search">
    <div class="search-title">Expert advices for parenting and more!</div>
    <form action="<?= $block->getUrl('kbase/article/s')?>" method="GET" id="kb-s-form">
        <input name='s' id='s' type="text" placeholder="Search..." class="form-control input-text required-entry" required value="<?= $block->getQuery() ?>">
        <button class="action primary" title="Submit" type="submit">
            <span><i class="fa fa-fw fa-search"></i></span>
        </button>
    </form>
</div>

