<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_ProductStockAlert
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/* @var $block \Bss\ProductStockAlert\Block\Product\View */
?>
<?php if($block->checkCustomer()): ?>
    <?php if(!$block->getStatusAvailable()): ?>
        <?php $message = $block->getNotificationMessage() ? $block->getNotificationMessage() : 'Notify me when this product is in stock'; ?>
        <div class="stockalert" id="block-stockalert">
            <div class="title" data-role="title">
                <strong id="block-stockalert-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __($message) ?></strong>
            </div>
            <div class="content" id="form-container" data-role="content" aria-labelledby="block-stockalert-heading">
                <form id="stockalert-form"
                      action="<?php /* @escapeNotVerified */ echo $block->getAction(); ?>"
                      method="post"
                      data-mage-init='{"productStockalert":{
                            "stockAlertEmail": "#stockalert_email",
                            "applyButton": "button.action.notify",
                            "cancelButton": "button.action.cancel"
                        }
                      }'>
                    <?php if (!$block->hasEmail($block->getProductIdController())): ?>
                    <div class="bss_productstockaler applied">
                        <div class="field">
                            <div class="control">
                                <input type="text" class="input-text" id="stockalert_email" name="stockalert_email" value="<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>" placeholder="<?php echo $block->escapeHtml(__('Your Email'));?>" />
                            </div>
                        </div>
                        <div class="actions-toolbar padding">
                            <div >
                                <button class="action notify primary" type="button" value="<?php /* @escapeNotVerified */ echo __('Notify') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Notify Me') ?></span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <?php else: ?>
                        <div class="bss_productstockaler">
                            <button  type="button" class="action cancel primary" value="<?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?>"><span><?php /* @escapeNotVerified */ echo __('Stop Notify') ?></span></button>
                        </div>
                    <?php endif; ?>
                </form>
            </div>    
        </div>
    <?php else: ?>
        <div class="container-child-product">
        </div>
    <?php endif; ?>
<?php endif; ?>
