
<?php $rturl=$_SERVER['REQUEST_URI'];
      $urlarr=explode('/',$rturl);
	  $itemupdate=0;
      if(in_array('checkout',$urlarr) && in_array('cart',$urlarr) && in_array('product_id',$urlarr)){
		  $itemupdate=1;
	  }
 ?>		
<script>
    require(['jquery'],function(jQuery){
        jQuery(document).ready(function(){
			<?php if($itemupdate==0){ ?>
            jQuery('#product_addtocart_form').submit(function( event ){
				event.preventDefault();
            });
			<?php } ?>
			jQuery(document).on("click",".showcart",function() {
				jQuery('.showcart').addClass("clicked");
			});
			jQuery(document).on("submit",".prod-list-form",function(event) {
				event.preventDefault();
            });
        });
    });
</script>
<style type="text/css">
  .prd_thumb_list li{
    overflow: hidden;
    
  }
  .sideimage{
        max-height: 412px;
    width: 97px;
    float: left;
    position: fixed;
    /*overflow: hidden;*/
    overflow-y: scroll;
}
.sidediv{
  width: 98px;overflow: hidden;float: left;height: 411px;
}
#div.sidediv :hover {
    width: 98px;
    overflow: hidden;
    float: left;
    height: 411px;
    overflow-y: scroll;
}

  }
</style>
<!--====footer=====-->

 <?php
    $objectManager  = \Magento\Framework\App\ObjectManager::getInstance();        
    $request        = $objectManager->get('\Magento\Framework\App\Request\Http');
    $storeManager   = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $store          = $storeManager->getStore();
    $baseurl        = $store->getBaseUrl();
    $model          = $objectManager->get('\Bluethink\Dailydose\Model\ResourceModel\Brand\Collection');
    $controller_name = $request->getControllerName();
  ?>

<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <div id="popup1" class="modal-box">
      <a href="javascript:void(0)" class="js-modal-close close">×</a>
      <div id="quickview" ></div>
    </div>

    <div class="brand-text">
      <span class="text-brand">Trusted Global Brands</span>
      <span id="back-to-top"><i class="fa fa-angle-up"></i></span>
    </div>
  <footer class="footer clearfix">
<div class="container">

<div class="brand-slider">
<div id="brands" class="owl-carousel owl-theme"><!--=======item====-->
<?php foreach ($model as $value) { 
  ?>
<div class="item"><a href="<?php echo $value['brand_url'] ;?>"><span class="brand-images"><img src="<?php echo $block->getUrl().'pub/media/bluethink/brand/images'.$value->getImage(); ?>" alt="" /></span></a></div>
<?php }   
?>
</div>
</div>
<div class="footer-links clearfix">
<div class="link-box link-box-one">
<h3>Information Links</h3>
<ul class="effect">
<li><a href="<?php echo $baseurl.'about_us'; ?>"><i class="fa fa-angle-right"></i> About Us</a></li>
<li><a href="<?php echo $baseurl.'nuluv-brands'; ?>"><i class="fa fa-angle-right"></i> Brands</a></li>
<li><a href="<?php echo $baseurl.'certificates-badges'; ?>"><i class="fa fa-angle-right"></i> Certificates and Badges</a></li>
<li><a href="<?php echo $baseurl.'press-media-coverage'; ?>"><i class="fa fa-angle-right"></i> Press and Media, Rewards</a></li>
<!-- <li><a href="<?php //echo $baseurl.'testimonials'; ?>"><i class="fa fa-angle-right"></i> Testimonials</a></li> 
 <li><a href="<?php //echo $baseurl.'rewardspoints'; ?>"><i class="fa fa-angle-right"></i> Rewards Program</a></li>
<li><a href="<?php //echo $baseurl.'rewardspoint'; ?>"><i class="fa fa-angle-right"></i> Rewards Program</a></li> -->
<li><a href="<?php echo $baseurl.'rewardspoint'; ?>"><i class="fa fa-angle-right"></i> Rewards Program</a></li>
<li><a href="<?php echo $baseurl.'faq/index/index'; ?>"><i class="fa fa-angle-right"></i> Help and FAQs</a></li>


</ul>
</div>
<div class="link-box link-box-two">
<h3> </h3>
<ul class="effect">
<li><a href="<?php echo $baseurl.'customer/account/login/'; ?>"><i class="fa fa-angle-right"></i> My Account</a></li>
<li><a href="<?php echo $baseurl.'checkout/cart'; ?>"><i class="fa fa-angle-right"></i> My Cart</a></li>
<li><a href="<?php echo $baseurl.'sales/order/history'; ?>"><i class="fa fa-angle-right"></i> Order Status</a></li>
<li><a href="<?php echo $baseurl.'shipping_returns'; ?>"><i class="fa fa-angle-right"></i> Shipping and Returns</a></li>
<li><a href="<?php echo $baseurl.'terms_conditions'; ?>"><i class="fa fa-angle-right"></i> Terms and Conditions</a></li>
<li><a href="<?php echo $baseurl.'contact_us'; ?>"><i class="fa fa-angle-right"></i> Contact Us</a></li>

<!-- <li><a href="<?php echo $baseurl.'rewardspoint'; ?>"><i class="fa fa-angle-right"></i> My Rewards</a></li>
<li><a href="<?php echo $baseurl.'#'; ?>"><i class="fa fa-angle-right"></i> Customer Service</a></li>
<li><a href="<?php echo $baseurl.'terms_conditions'; ?>"><i class="fa fa-angle-right"></i> Terms & Policie</a></li>
<li><a href="<?php echo $baseurl.'contact_us'; ?>"><i class="fa fa-angle-right"></i> Contact us</a></li> -->
</ul>
</div>
<div class="link-box link-box-three">
<h3>Trending Searches</h3>
<div class="tags">
<?php 
     $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
     $_productCollection = $productCollection->create()->addAttributeToSelect('*')->addAttributeToFilter('product_tags', array('neq' => ''))->load();
	 $alltag=array();
	 if (count($_productCollection)>0){ 
		  foreach ($_productCollection as $_product){
			  $product_tags=$_product->getProductTags();
			  $tagcoll=explode(',', $product_tags);
			  if(count($tagcoll)>0){
				  foreach($tagcoll as $tag){
					  $tag = ltrim($tag);
					  if(!in_array($tag,$alltag)){
						  $alltag[]=$tag;
					      echo '<a href="'.$baseurl.'tag/'.urlencode(preg_replace('/\-{1,}/', '-', preg_replace('/\s{1,}/', '-', $tag))).'.html">'.$tag.'</a>';
					  }
					  
				  }
			  }
		  }
     }
 ?>
</div>
</div>
<?php 
echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml();
?>
<div class="soci">
<ul class="social-footer">
  <li><span>#nuluv</span></li><br>
  <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social_icon')->toHtml();?>
  <p>1800 - 120 - LOVE (5683)</p>
  <a class="support-email" href="mailto:support@nuluv.in" target="_top">support@nuluv.in</a>
</ul>
<!-- <div class="'pro"><img src="<?php //echo $this->getViewFileUrl('images/created_by.png'); ?>" alt="" /></div> -->
</div>
</div>

<div class="footer-middle-section">
<ul class="footer-middle-inner">
<li class="footer-middle-lft"><a href="#"><i class="fa fa-credit-card" aria-hidden="true"></i> Hassle Free Domestic Payments</a></li>
<li class="footer-middle-center"><a href="#"><i class="fa fa-truck" aria-hidden="true"></i> Products ship from nuluv warehouse in Delhi</a></li>
<li class="footer-middle-rgt"><a href="#"><i class="fa fa-retweet" aria-hidden="true"></i> Easy Returns</a></li>
</ul>
</div>
<div class="copyright clearfix">
<ul>
<li class="copyright-lft">Copyright © 2017 Nuluv – All Rights Reserved.</li>
<li class="copyright-center"><img src="<?php echo $this->getViewFileUrl('images/payment-card.png'); ?>" alt="" /></li>
<li class="copyright-rgt">Site By <a href="#" target="_blank"><img src="<?php echo $this->getViewFileUrl('images/dl.png'); ?>" alt="" /></a></li>
</ul>
</div>
</div>

</footer>

  <script type="text/javascript">

          require(['jquery'],function(jQuery){
           
			  var b = jQuery('#back-to-top');
			  //b.hide();
			  b.on('click',function(e){
				e.preventDefault();
				jQuery('html,body').animate({
				  scrollTop: 0
				}, 700);
			  });
			  
			  var $win = jQuery(window);   
			  $win.scroll(function () { 
				/*alert('fgfgffghf');*/
				var footer_pos =  (jQuery(".footer").offset().top - jQuery(window).innerHeight()) - jQuery(document).scrollTop();
				if ($win.scrollTop() > 300) {
				  b.fadeIn();
				  //console.log("fadding in")
				} 
				else {
				  b.fadeOut();
				}
				
				if(footer_pos < 0){
				  b.css("position","absolute");
				}else{
				  b.css("position","fixed");
				}
			  });
			});
        
    </script> 
    <script>
    
    
  require(['jquery'],function (jQuery) {
    jQuery(document).ready(function(){

    jQuery(".search-icon").click(function(){

    //alert(this.id); 
    jQuery("#popup1").css({ 'top': "32.5px" });
    var id=this.id;
    var controller='<?php echo $controller_name; ?>';
    jQuery.ajax({
      url: "<?php echo $block->getUrl('custom/index/quickview/');?>",
      showLoader: true,
      type: 'POST',
      data: {id:id,controller:controller},
      success: function(rs)
      {
        //alert(rs);
        document.getElementById("quickview").innerHTML=rs;
        jQuery("#popup1").css({ 'display': "block" });
       
      
     }
    });
  });
    var appendthis =  ("<div class='modal-overlay js-modal-close'></div>");
  jQuery('a[data-modal-id]').click(function(e){
  e.preventDefault();
    jQuery("body").append(appendthis);
    jQuery(".modal-overlay").fadeTo(500, 0.7);
    //$(".js-modalbox").fadeIn(500);
    var modalBox = jQuery(this).attr('data-modal-id');
    jQuery('#'+modalBox).fadeIn(jQuery(this).data());
  });
  jQuery(".js-modal-close, .modal-overlay").click(function() {
    jQuery(".modal-box, .modal-overlay").fadeOut(500, function() {
      jQuery(".modal-overlay").remove();
    }); 
  }); 
  jQuery(window).resize(function() {
    jQuery(".modal-box").css({
      top: (jQuery(window).height() - jQuery(".modal-box").outerHeight()) / 2,
      left: (jQuery(window).width() - jQuery(".modal-box").outerWidth()) / 2
    });
  }); 
  jQuery(window).resize();
  });
    jQuery('#thumbs li').delegate('img','click', function(){
  jQuery('#largeImage').attr('src',jQuery(this).attr('src').replace('thumb','large'));
  //$('#description').html($(this).attr('alt'));
});


 });

function newsletterSubmit(event){
  event.preventDefault();
  require(['jquery'],function(jQuery){
    var url = jQuery('#newsletter-validate-detail').attr('action');
    var form = jQuery('#newsletter-validate-detail').serialize();
    var emailid = jQuery('#newsletter').val();
    email_regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;
    if(email_regex.test(emailid)){
      // alert(url);
      // alert(form);
      jQuery.ajax({
                  showLoader: true,
                  url: url,
                  data: form,
                  type: "POST",
              }).done(
                  function (response) {
                      console.log(response);
                      jQuery('#news_msg').show();
                      jQuery('#news_msg').html(response);
                      jQuery('#newsletter').val('');
                      setTimeout(function(){ jQuery('#news_msg').hide(); }, 3000);
                  }
              );
    }

  });
}
</script>
<script>
        require(["jquery"],function(jQuery){
            jQuery(document).ready(function(){
                jQuery("#22222").click(function(){
                    alert("The paragraph was clicked.");
                });
            });
        });
    </script>

      <script type="text/javascript">
       function invokehello(id)
       {
        
        var replacerc=document.getElementById("largeImage");
        replacerc.src=id.getAttribute('src');
        console.log("*********"+id);
        
       }
    </script>

    <script type="text/javascript">
      require(["jquery"],function(jQuery){
		  
			jQuery(window).load(function() {
			  setTimeout(function(){jQuery('.toolbar-products').css("display", "block"); }, 5000);
			});			
       
		jQuery('.sublink').click(function(){
			jQuery(this).toggleClass('open');
			jQuery(this).siblings('.megamenu').slideToggle();
			/*jQuery('.megamenu').slideToggle();*/
		});

		if (window.matchMedia('(max-width: 767px)').matches){
		jQuery('.trigger-opn').click(function() {
			jQuery(this).parent().siblings('.open-submenu').find('.trigger-opn').removeClass('activate');
			jQuery(this).parent().siblings('.open-submenu').find('.open-submenu').slideUp(250);
			jQuery(this).next('.open-submenu').slideToggle(250);
			jQuery(this).next('.open-submenu').children('.open-submenu').find('.open-submenu').slideUp(250);
			jQuery(this).next('.open-submenu').children('.open-submenu').find('.trigger-opn').removeClass('activate');
			jQuery(this).toggleClass('activate');
			return false;
		});
		}
	});
</script>        
 <script>
	require(["jquery"],function(jQuery){
		
		jQuery(".login").hover(function(){
			jQuery('#login-form').show();
		},function(){
			jQuery('#login-form').hide();
		});
		/* jQuery(".login").hover(function() {
		    jQuery("#login-form").show();			
		});
		jQuery("#login-form").mouseout(function() {
		    jQuery("#login-form").hide();
		}); */
	});
</script> 
<script type="text/x-magento-init">
    {
        ".prod-list-form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<script>
  function openElements(evt, categorytype) {
    var i, storytabs, storyelelinks;
    storytabs = document.getElementsByClassName("storytabs");
    for (i = 0; i < storytabs.length; i++) {
        storytabs[i].style.display = "none";
		
    }
    storyelelinks = document.getElementsByClassName("storyelelinks");
    for (i = 0; i < storyelelinks.length; i++) {
        storyelelinks[i].className = storyelelinks[i].className.replace(" activele", "");
    }
    document.getElementById(categorytype).style.display = "block";
    document.getElementById(categorytype).style.animation = "quickanimatefade 1s";
    document.getElementById(categorytype).style.height = "600px";
    evt.currentTarget.className += " activele";
}






  jQuery(".storyelelinks").click(function(){
    jQuery(".oneleft").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.oneleft').removeClass('slideleft');
},1000);

});



jQuery(".storyelelinks").click(function(){
    jQuery(".oneright").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.oneright').removeClass('slideleft');
},1000);

});


jQuery(".storyelelinks").click(function(){
    jQuery(".innerright").toggleClass('slideright');

    jQuery(".innerleft").toggleClass('slideright');

      jQuery(".halftopdv").toggleClass('slidhalfrgt');

});


jQuery(".storyelelinks").click(function(){
     setTimeout(function() {
    jQuery('.totinr').removeClass('slideleft');
},1000);

});



jQuery(".storyelelinks").click(function(){
    jQuery(".totinr").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.totinr').removeClass('slideleft');
},1000);

});


jQuery(".storyelelinks").click(function(){
    jQuery(".onetopleft").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.onetopleft').removeClass('slideleft');
},1000);

});

jQuery(".storyelelinks").click(function(){
    jQuery(".onemd").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.onemd').removeClass('slideleft');
},1000);

});

jQuery(".storyelelinks").click(function(){
    jQuery(".twomd").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.twomd').removeClass('slideleft');
},1000);

});

jQuery(".storyelelinks").click(function(){
    jQuery(".onetopright").toggleClass('slideleft');

    setTimeout(function() {
    jQuery('.onetopright').removeClass('slideleft');
},1000);

});


    

setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div.tofive").toggleClass("slideleft");

}, 2000);


setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div.innerleft").toggleClass("slideright");

}, 2000);

setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div.halftopdv").toggleClass("slidhalfrgt");

}, 2000);

setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div.innerright").toggleClass("slideright");

}, 2000);

setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div.totinr").toggleClass("brf");

}, 2000);


setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div#All").addClass("showthis");

}, 2000);

setInterval(function(){ 
    //alert("Hello"); 
    jQuery("div#All").removeClass("showthis");

}, 2000);




var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("storytabs");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 4000); // Change image every 2 seconds
}

function openCondtion(condtionType) {

	var elems = document.querySelectorAll(".w3-bar-item.w3-button");

	[].forEach.call(elems, function(el) {
		el.classList.remove("current");
	});
	
	document.getElementById(condtionType+'s').className += " current";
    var i;
    var x = document.getElementsByClassName("concerned");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
	
    document.getElementById(condtionType).style.display = "block";  
}


function openMedia(condtionMode) {
    var i;
    var x = document.getElementsByClassName("mediacover");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    document.getElementById(condtionMode).style.display = "block";  
}


function openStory(condtionType) {
    var i;
    var x = document.getElementsByClassName("Storyset");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    document.getElementById(condtionType).style.display = "block";  
}


 jQuery(function () {
	jQuery('.tabs-medias li').click(function() {
		jQuery(this).addClass('active').siblings().removeClass('active');
	});
})


jQuery(function () {
    jQuery('.w3-bar button').click(function() {
    jQuery(this).addClass('active').siblings().removeClass('active');
});
})


 jQuery("div.main").toggleClass("content-para");
</script>