<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php /* if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit"
       href="<?php  echo $block->getConfigureUrl() ?>"
       title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>">
        <span>
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            
        </span>
   </a>
<?php endif */ ?>
