<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php //echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();   ?>

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Form\Register')->setTemplate('Magento_Customer::form/register.phtml')->toHtml();?>



<style type="text/css">
    .mage-error[generated]{
        margin-bottom: 12px;
    }
</style>

