<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
$topics = $block->getDisplayTopics();
?>
<div class="forum-list-container controls-exists clearfix">
  <!-- <h3 class="grid-title">
    <?php //if ($block->getIsIconsEnabled() && $block->getIconSrc()): ?>
      <img src="<?php //echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . $block->getIconSrc()) ?>" />
    <?php //endif; ?>
    <?php //echo __('View Forum "%1"', $block->getForumTitle()) ?>
  </h3> -->
  <div class="forum-grid-controls">
    <button onclick="document.location.href = '<?php echo $block->getAddNewUrl() ?>'" class="action primary" title="<?php echo __('Add Topic') ?>">
      <span><?php echo __('Add Topic') ?></span>
    </button>
  </div>
  <div class="clearfix">&nbsp;</div>
  <?php if (!$topics || !$topics->getSize()): ?>
    <div class="forum-grid-no-data">
      <?php echo __('No Data Found') ?>
    </div>
  <?php else: ?>
    <!-- <div class="toolbar top forum-toolbar">
      <?php //echo $block->getPagerHtml(); ?>
    </div> -->

    <!-- <div class="forum-sort">
      <?php //echo __('Sort By') ?>
      &nbsp;&nbsp;
      <a <?php //echo ($this->getSortType() == 'asc' ? 'class="selected"' : '') ?> href="<?php //echo $block->getSortUrl(null, 'asc') ?>"><?php //echo __('Oldest') ?></a>
      &nbsp;|&nbsp;
      <a <?php //echo ($this->getSortType() == 'desc' ? 'class="selected"' : '') ?> href="<?php //echo $block->getSortUrl(null, 'desc') ?>"><?php //echo __('Newest') ?></a>
    </div> -->
	<!-- forum -->
    <ul class="forum-grid forum-list grid data-table-forum-resp">
      <li class="bbp-header-cls">
         <ul class="forum-titles-cls">
          <li class="bbp-forum-info-cls"><?php echo __('Topic') ?></li>
          <li class="bbp-forum-topic-count-cls"><?php echo __('Posts') ?></li>
          <li class="bbp-forum-reply-count-cls"><?php echo __('Views') ?></li>
          <li class="bbp-forum-freshness-cls"><?php echo __('Freshness') ?></li>
        </ul>
      </li>
      <li class="bbp-body-cls">
        <?php foreach ($topics as $topic): ?>
          <ul class="loop-item-cls">
            <li class="bbp-forum-info-cls">
              <div>
                <div class="forum-icons">
                  <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'forum_post-icon.png'); ?>" />
                  <?php if ($block->getIsIconsEnabled() && $block->getIconSrc($topic, true)): ?>
                    <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . $block->getIconSrc($topic, true)) ?>" />
                  <?php endif; ?>
                </div>
                <div class="forum-details sdds">
                  <a class="forum-display-description" href="<?php echo $block->getTopicViewUrl($topic); ?>">
                    <?php echo $topic->getTitle() ?>
                  </a>
                  <?php if ($topic->getDescription()): ?>
                    <div class="forum-topic-description">
                      <?php echo $topic->getDescription() ?>
                    </div>
                  <?php endif; ?>
                  <!-- <div class="forum-created-time">
                    <?php //echo __('Created') ?>: <?php //echo $block->getTimeAccordingToTimeZone($topic->getCreatedTime()); ?>
                  </div> -->
                  <!-- <div class="forum-created-by">
                    <?php //echo __('Created By: "<a href=%2>%1</a>"', $block->getTopicCreatorName($topic), $block->getTopicCreatorLink($topic)) ?>
                  </div> -->
                  <?php if ($block->getIsOwner($topic)): ?>
                    <div class="forum-topic-controls">
                      <a href="<?php echo $block->getEditLink($topic) ?>" class="forum-topic-controls-edit">
                        <!-- <img src="<?php //echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'edit_icon.png'); ?>" /> -->
                        <?php echo __('Edit') ?>
                      </a>
                      &nbsp;
                      <?php if ($block->getIsCustomerAllowedDeleteTopics()): ?>
                        <a href="<?php echo $block->getDeleteLink($topic) ?>" class="forum-topic-controls-delete">
                          <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'delete_icon.png'); ?>" />
                          <?php echo __('Delete') ?>
                        </a>
                      <?php endif; ?>
                    </div>
                  <?php endif; ?>
                </div>
              </div>
            </li>
            <li class="bbp-forum-topic-count-cls">
              <div class="total-posts-container">
                <!-- <img src="<?php //echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'forum_post.png'); ?>" /> -->
                <?php echo $topic->getTotalPosts() ?>
              </div>
            </li>
            <li class="bbp-forum-reply-count-cls">
              <div class="total-views-container">
                <!-- <img src="<?php //echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'view_icon.png'); ?>" /> -->
                <?php echo $topic->getTotalViews() ? $topic->getTotalViews() : '0'; ?>
              </div>
            </li>
            <li class="bbp-forum-freshness-cls">
              <?php
              $latest = $block->getLatestPostDetails($topic->getLastPostId());
              ?>
              <div class="forum-latest-reply">
                <?php if (!$latest): ?>
                  <?php echo __('No Data Found'); ?>
                <?php else: ?>
                  <?php /* if ($block->getIsIconsEnabled() && $block->getLatestIcon($latest)): ?>
                    <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . $block->getLatestIcon($latest)) ?>" />
                  <?php endif; ?>
                  <a class="forum-display-description" href="<?php echo $block->getLatestViewUrl($latest); ?>"><?php echo $block->getLatestTopicTitle($latest); ?></a>
                  <?php if ($block->getLatestTopicDescription($latest)): ?>
                    <div class="forum-topic-description">
                      <?php echo $block->getLatestTopicDescription($latest) ?>
                    </div>
                  <?php endif; */ ?>
				  <?php $userDetails = $block->getUserDetails($latest); ?>
				  <div class="forum-latest-reply-user">
				     <?php 
					     if($userDetails['avatar']){
							 echo '<img src="'.$userDetails['avatar'].'" height="50" width="50" class="forum-avatar-image" />';
						 }
					 ?>
                  </div>
                  <div class="uploader-container-cls">
						<div class="uploader-cls">
							<?php
							  echo __('<strong><a href="%1">%2</a></strong>', $block->getLatestPostedByUrl($latest), $block->getLatestPostedBy($latest));
							  ?>
						</div>
						<div class="forum-latest-reply-date">
						        <?php 
								    $postdate=$block->getLatestPostedDate($latest);
									$ltpostdate = new DateTime($postdate);
									$latestdate=$ltpostdate->format('Y-m-d H:i:s');
									$currdatetime =  date('Y-m-d H:i:s');
								    $datetime1 = new DateTime($latestdate);
									$datetime2 = new DateTime($currdatetime);
									$interval = $datetime1->diff($datetime2);
									$days=$interval->format('%R%a');
									$hours=$interval->format('%R%H');
									$minute=$interval->format('%R%i');
									$second=$interval->format('%R%s');
									$dyears=$interval->format('%R%y');
									$dmonths=$interval->format('%R%m');
									if($dyears>0 && $dmonths>0){
									   echo str_replace('+','',$dyears).' Year, '.str_replace('+','',$dmonths).' Months ago';	
									}elseif($dmonths>0 && $days>0){
									   echo str_replace('+','',$dmonths).' Month, '.str_replace('+','',$days).' Days ago';	
									}elseif($days>0 && $hours>0){
									   echo str_replace('+','',$days).' Days, '.str_replace('+','',$hours).' Hours ago';	
									}elseif($hours>0 && $minute>0){
									   echo str_replace('+','',$hours).' Hours, '.str_replace('+','',$minute).' Minutes ago';	
									}elseif($minute>0 && $second>0){
									   echo str_replace('+','',$minute).' Minutes, '.str_replace('+','',$second).' Seconds ago';	
									}else{
									   echo str_replace('+','',$second).' Seconds ago';	
									}
									$date = new DateTime($postdate);
									$postdate1 =  $postdate;
									$currdate =  date('Y-m-d');
									?>
								<?php /* custom */ 
									$start = strtotime($postdate1);
									$end = strtotime($currdate);
									$total_days = ceil(abs($end - $start) / 86400);
									$full_year =  $total_days/365;
									$year =  Intval($total_days/365);
									$month = intval( $total_days/30);
									$months = $actual_month = intval($month/12);
									//echo $year.' Year, '.$months.' months ago';
								?>
								<?php /* End: custom */ ?>
						</div>
					</div>
                <?php endif; ?>  
              </div>
            </li>
          </ul>
        <?php endforeach; ?>
      </li>
    </ul>
    <script type="text/javascript">
      WIO_Forum_Responsive_tables.init();
    </script>
  <?php endif; ?>
</div>