<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Quickview
 */
?>
<script>
    require([
        'jquery',
        'Amasty_Quickview/js/amquickview'
    ], function ($) {
        $('.product-items .product-item .product-item-info .product-image').each(function( key, element ) {
            $(element).amQuickview(<?php echo $this->javascriptParams(); ?>);
        });
    });
</script>


