<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
  $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
  $request = $objectManager->get('\Magento\Framework\App\Request\Http');
  $action_name = $request->getActionName();
  $module_name = $request->getModuleName(); 
  $controller_name = $request->getControllerName();
  $customerSession = $objectManager->get('Magento\Customer\Model\Session');
  $wishlist_id=array();
  if($customerSession->isLoggedIn())
  {
    $customerid=$customerSession->getCustomer()->getId();
    $Wishlist_Model = $objectManager->create('\Magento\Wishlist\Controller\WishlistProviderInterface'); 
    $currentUserWishlist = $Wishlist_Model->getWishlist();
    if ($currentUserWishlist)
    {
      $wishlistItems = $currentUserWishlist->getItemCollection()->getData();
      foreach ($wishlistItems as  $wishlistItems_value) 
      {
        $wishlist_id[]=$wishlistItems_value['product_id'];
      }
    }
  }

//   if ($controller_name=="result" && $module_name=="catalogsearch") 
//   { }else
//   {
//     $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
//     $categoryHelper = $this->helper('Magento\Catalog\Helper\Category');
//     $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository'); 
//     $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
//     $categoryId=$category->getId();
//     $categoryname=$category->getName();
//     $catalogSession = $objectManager->get('\Magento\Catalog\Model\Session');
//        if ($categoryId==3 || $categoryId==4 || $categoryId==5 ) {
   
//       $catalogSession->setCatid($categoryId);
//   } 
//   $catid=$catalogSession->getCatid();
//   $categoryurl=$category->getUrl();
//   $category = $categoryFactory->create()->load($catid);
//   $childrenCategories = $category->getChildrenCategories();
// }
  $_productCollection = $block->getLoadedProductCollection();
  $_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<section class="container">
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
    if ($controller_name=="result" && $module_name=="catalogsearch") { 
  }else{ echo $block->getToolbarHtml(); } ?>
    <?php echo $block->getAdditionalHtml(); ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="clearfix"></div>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> tab-content current">
        <?php $iterator = 1; ?>
        <?php  if ($module_name=="catalogsearch") { ?>
            <h2 class="head-title serch-devider">Products Found</h2>
       <?php } ?>
        
          <ul class=" product_list products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-box product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php
                      $contractDateBegin=$_product['news_from_date'];
                      $contractDateEnd=$_product['news_to_date'];
                      date_default_timezone_set('Asia/Kolkata');
                      $paymentDate = date('Y-m-d H:i:s');
                    ?>
                    <div class="product-image">
                    <?php  if (($paymentDate > $contractDateBegin) && ($paymentDate < $contractDateEnd))
                        { ?>
                          <div class="new-items">New</div>
                       <?php }
                        else
                        { ?>
                       <?php } ?>
                      <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    
                     
                        <?php if ($_product->getIsSalable()): ?>
                           <div class="overlay">
                        <div class="overlay-content"><a href="javascript:void(0)"  id='<?php echo $_product->getId();?>' class="search-icon"><i class="fa fa-search" ></i></a><a class="quick-icon" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><i class="fa fa-arrow-right" ></i></a>
                        </div>
                        </div>
                         <?php else: ?>
                          <div class="overlay sold-out">
                        <div class="overlay-sold-out-content"><a class="sold-out-btn" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">Sold Out</a></div>
                      </div>
                      <a class="get-info">Get Info</a>
                        <?php endif; ?>
                      
                    </div>
                    
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h5>
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h5>
                        
                        <p class="p-price"><?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?></p>
                       
                
                    </div>
                    
                </div>
                <span class="cta"> 
                  <b><a href="<?php echo $block->getUrl('wishlist',['_secure' => true]); ?>" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action to wishlist" data-action="add-to-wishlist">
                    <?php
                    if ($customerSession->isLoggedIn()) {
                      if (!in_array($_product->getId(), $wishlist_id )) { ?>
                    <i class="fa fa-heart-o"><?php }else{ ?> <i class="fa fa-heart"> <?php  } }else{ ?><i class="fa fa-heart-o"><?php } ?></i>
                  </a></b>
                <?php $RatingOb = $objectManager->create('Magento\Review\Model\Rating')->getEntitySummary($_product->getId());?>
                <b><a href='<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>'><i class="fa fa-comment-o"> (<?php
                          if ($RatingOb->getCount()) {
                            echo $RatingOb->getCount();
                           }else{echo '0';}?>)</i></a></b> 
                    <div class="product-details btlist-cart" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit" title="Add to Cart" class="p-product-add">
                                            <span><i class="fa fa-shopping-cart"></i></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                          </div>
                      </span>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php ///echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
       <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php //if ($categoryId==3 || $categoryId==4 || $categoryId==5 ) { ?>
<script>
 require(['jquery'],function (jQuery) {
    jQuery(document).ready(function(){
      // jQuery(".layer-input-filter").click(function(){
       
      //   jQuery(this).prev('a').click();
      //   alert("ji");
      //   if(jQuery(this).is(':checked'))

          
      //    //   alert('checked');
      //     //jQuery(this).prop('checked', true);

      //   else
      //       alert('unchecked');
      //   //alert("kaba");
      // });
      //alert("jiji");
     //jQuery('.toolbar-products').css("display", "block");
     //jQuery('.tab-link:first').addClass('current');
    });
    
});
</script>

<?php
//} ?>
        
    <?php endif; ?>
<?php endif; ?>
</section>
<script>
//  require(['jquery'],function (jQuery) {
//    jquery(window).load(function(){
//     alert("hu");
// jquery(function () {
//     if (jquery('#layered-filter-block').hasClass('.filter')) {
//       alert('a-->');
//         jquery('.orderby').addClass("top65");
//     }else{
//       alert('b-->');
//       jquery('.orderby').addClass("top0");
//     }
// });
// });
    
// });
</script>
