<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
$forums = $block->getDisplayForums();
?>
<div class="forum-list-container clearfix">
  <h3 class="grid-title">
    <?php echo __('Viewing All Forums') ?>
  </h3>
  <?php if (!$forums->getSize()): ?>
    <div class="forum-grid-no-data">
      <?php echo __('No Data Found') ?>
    </div>
  <?php else: ?>
    <div class="toolbar top forum-toolbar">
      <?php echo $block->getPagerHtml(); ?>
    </div>
    <div class="forum-sort">
      <?php echo __('Sort By') ?>
      &nbsp;&nbsp;
      <a <?php echo ($this->getSortType() == 'asc' ? 'class="selected"' : '') ?> href="<?php echo $block->getSortUrl('asc') ?>"><?php echo __('Oldest') ?></a>
      &nbsp;|&nbsp;
      <a <?php echo ($this->getSortType() == 'desc' ? 'class="selected"' : '') ?> href="<?php echo $block->getSortUrl('desc') ?>"><?php echo __('Newest') ?></a>
    </div>
    <table class="forum-grid forum-list grid data-table-forum-resp">
      <thead>
        <tr>
          <th width="35%"><?php echo __('Forum') ?></th>
          <th width="15%"><?php echo __('Total Topics') ?></th>
          <th width="15%"><?php echo __('Total Posts') ?></th>
          <th width="35%"><?php echo __('Latest Reply') ?></th>
        <tr>
      </thead>
      <tbody>
        <?php foreach ($forums as $forum): ?>
          <tr>
            <td>
              <div>
                <div class="forum-icons">

                  <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'folder_forum.png'); ?>" />
                  <?php if ($block->getIsIconsEnabled() && $block->getIcon($forum)): ?>
                    <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . $block->getIcon($forum)) ?>" />
                  <?php endif; ?>
                </div>
                <div class="forum-details">
                  <?php if (!$block->isAllowed($forum->getId()) && !$block->getIsModerator()): ?>
                    <strong><?php echo $forum->getTitle() ?></strong>
                  <?php else: ?>
                    <a class="forum-display-description" href="<?php echo $block->getForumViewUrl($forum); ?>"><?php echo $forum->getTitle() ?></a>
                  <?php endif; ?>
                  <?php if ($forum->getDescription()): ?>
                    <div class="forum-topic-description">
                      <?php echo $forum->getDescription() ?>
                    </div>
                  <?php endif; ?>
                  <div class="forum-created-time">
                    <?php echo __('Created') ?>: <?php echo $block->getTimeAccordingToTimeZone($forum->getCreatedTime()); ?>
                  </div>
                  <div class="forum-created-by">
                    <?php echo __('Created By: "<a href=%2>%1</a>"', $block->getForumCreatorName($forum), $block->getForumCreatorLink($forum)) ?>
                  </div>
                </div>
              </div>
            </td>
            <td>
              <div class="total-topics-container">
                <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'folder_topic.png'); ?>" />
                <?php echo $forum->getTotalTopics() ?>
              </div>
            </td>
            <td>
              <div class="total-posts-container">
                <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'forum_post.png'); ?>" />
                <?php echo $forum->getTotalPosts() ?>
              </div>
            </td>
            <td>
              <?php
              $latest = $block->getLatestPostDetails($forum->getLastPostId());
              ?>
              <div class="forum-latest-reply">

                <?php if (!$block->isAllowed($forum->getId())  && !$block->getIsModerator()): ?>
                  <strong><?php echo __('Private Forum') ?></strong>
                <?php else: ?>
                  <?php if (!$latest): ?>
                    <?php echo __('No Data Found'); ?>
                  <?php else: ?>
                    <?php if ($block->getIsIconsEnabled() && $block->getLatestIcon($latest)): ?>
                      <img src="<?php echo $block->getViewFileUrl('WIO_Forum' . DIRECTORY_SEPARATOR . $block->getLatestIcon($latest)) ?>" />
                    <?php endif; ?>
                    <a class="forum-display-description" href="<?php echo $block->getLatestViewUrl($latest); ?>"><?php echo $block->getLatestTopicTitle($latest); ?></a>
                    <?php if ($block->getLatestTopicDescription($latest)): ?>
                      <div class="forum-topic-description">
                        <?php echo $block->getLatestTopicDescription($latest) ?>
                      </div>
                    <?php endif; ?>
                    <div class="forum-latest-reply-date">
                      <?php echo __('Posted: <strong>%1</strong>', $block->getLatestPostedDate($latest)); ?>
                    </div>
                    <div class="forum-latest-reply-user">
                      <?php
                      echo __('Posted By: <strong><a href="%1">%2</a></strong>', $block->getLatestPostedByUrl($latest), $block->getLatestPostedBy($latest));
                      ?>
                    </div>
                  <?php endif; ?>  
                <?php endif; ?>
              </div>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    <script type="text/javascript">
      WIO_Forum_Responsive_tables.init();
    </script>
  <?php endif; ?>
</div>