<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php

/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cmsPage = $objectManager->get('\Magento\Cms\Model\Page');
$action_name = $request->getActionName();
$module_name = $request->getModuleName();
$controller_name = $request->getControllerName();
if ($action_name == 's' && $module_name == 'kbase' && $controller_name == 'article') {
    ?>
    <div class="orderby">
        <span>Order By</span>
        <select class="custom_select" id="sorter" data-role="sorter">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                            selected="selected"
                        <?php endif; ?>
                        >
                            <?php echo $block->escapeHtml(__($_order)) ?>
                </option>

            <?php endforeach; ?>
        </select>
    </div>

    <?php
}else {

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current category
    $categoryurl = $category->getUrl();
    $cat_url = $category->getUrl() . '?product_list_dir=asc';
    $cat_urldesc = $category->getUrl() . '?product_list_dir=desc';
    $cat_priceurlasc = $category->getUrl() . '?product_list_order=price&product_list_dir=asc';
    $cat_priceurldesc = $category->getUrl() . '?product_list_order=price&product_list_dir=desc';
    $cat_nameurlasc = $category->getUrl() . '?product_list_order=name&product_list_dir=asc';
    $cat_nameurldesc = $category->getUrl() . '?product_list_order=name&product_list_dir=desc';
    $cat_featured = $category->getUrl() . '?featured=6';

    $url = $_SERVER['REQUEST_URI'];
    $path = strstr($url, '?');
    ?>
<!--    <div class="orderby">
        <span><?php /* @escapeNotVerified */ echo __('Order By') ?></span>
        <select class="custom_select">
            <option>Featured</option>
            <option>Height to Low</option>
            <option>Low to Height</option>
            <option>Populer</option>
        </select>
    </div>-->
    <div class="orderby">
        <span><?php /* @escapeNotVerified */ echo __('Order By') ?></span>
        <select id="sorter" data-role="sorter" class="custom_select" onchange="productlistasc();" name="sorterone">
            <!--  <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <?php if ($_order != 'Position') : ?>
                                                                 <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                                                                                                 selected="selected"
                    <?php endif; ?>
                                                                     >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                                                                 </option>
                                                                 
                <?php endif; ?>
            <?php endforeach; ?> -->


            <option value="name&product_list_dir=asc" <?php if ($path == '?product_list_order=name&product_list_dir=asc') { ?> selected="selected"<?php }
            ?> ><?php echo __('Relevance'); ?></option>
            <option value="name&product_list_dir=desc" <?php if ($path == '?product_list_order=name&product_list_dir=desc') { ?> selected="selected"<?php }
            ?> ><?php echo __('Alphabetically, Z-A'); ?></option>

            <option value="&product_list_dir=asc" <?php if ($path == '?product_list_order=price&product_list_dir=asc') { ?> selected="selected"<?php }
            ?> ><?php echo __('Price, low to high'); ?></option>
            <option value="&product_list_dir=desc" <?php if ($path == '?product_list_order=price&product_list_dir=desc') { ?> selected="selected"<?php }
            ?> ><?php echo __('Price, high to low'); ?></option>   
        </select>
        <?php if ($block->getCurrentDirection() == 'desc'): ?>
            <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
                <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
            </a>
        <?php else: ?>
            <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
                <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
            </a>
        <?php endif; ?>
    </div>

<?php } ?>
<script>

    function productlistasc()
    {

        require(['jquery'], function(jQuery) {
            jQuery(document).ready(function() {
                if (document.getElementById('sorter').value == "name&product_list_dir=asc") {
                    window.location.href = '<?php echo $cat_nameurlasc ?>';
                }

                if (document.getElementById('sorter').value == "name&product_list_dir=desc") {
                    window.location.href = '<?php echo $cat_nameurldesc ?>';
                }

                if (document.getElementById('sorter').value == "&product_list_dir=asc") {
                    window.location.href = '<?php echo $cat_priceurlasc ?>';
                }

                if (document.getElementById('sorter').value == "&product_list_dir=desc") {
                    window.location.href = '<?php echo $cat_priceurldesc ?>';
                }
                if (document.getElementById('sorter').value == "featured") {
                    window.location.href = '<?php echo $cat_featured ?>';
                }



            });
        });

    }

</script>

