<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_ProductStockAlert
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="swatch-opt 323" data-role="swatch-options"></div>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "bss_configurable_control": {
                "jsonConfig": <?php /* @escapeNotVerified */ echo $swatchOptions = $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?php /* @escapeNotVerified */
                    echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>",
                "onlyMainImg": <?php /* @escapeNotVerified */ echo $block->getVar(
                    'change_only_base_image',
                    'Magento_Swatches'
                ) ?: 'false'; ?>,
                "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar(
                    'gallery_switch_strategy',
                    'Magento_ConfigurableProduct') ?: 'replace'; ?>",
                "jsonChildProduct": <?php echo $block->getJsonChildProductData(); ?>
            }
        }
    }
</script>
