<script src='https://www.google.com/recaptcha/api.js'></script>
<?php
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
   $baseurl = $storeManager->getStore()->getBaseUrl();
   $customerSession = $objectManager->create('Magento\Customer\Model\Session');
	$customername='';
	$customeremail='';
	$mobilenumber='';
	$tel = "";
	if ($customerSession->isLoggedIn()) {
		$customeremail=$customerSession->getCustomer()->getEmail();
		$customername=$customerSession->getCustomer()->getName();
		
		$customerID = $customerSession->getCustomer()->getId();
		$customerObj = $objectManager->create('Magento\Customer\Model\Customer')
		->load($customerID);
		//echo $customerEmail = $customerObj->getEmail();die;
		
		$customerAddress = array();

		foreach ($customerObj->getAddresses() as $address)
		{
			$customerAddress[] = $address->toArray();
		}

		
		foreach ($customerAddress as $customerAddres) {

			$tel = $customerAddres['telephone'];
		}
		
		
	}
 ?>
 
<div class="requirement-cls">
 <h2>Please fill your requirement<h2>
<form data-mage-init='{"validation": {}}' class="form" action="<?php echo $baseurl.'lookingfor'; ?>" id="custom-form" method="post" autocomplete="off">
   
	<fieldset class="fieldset">
		<div class="field name required">
			<label class="label" for="Name"><span>Name</span></label>
			<div class="control">
                <input name="name" id="name" title="name" value="<?php echo $customername; ?>" class="input-text" type="text" data-validate="{required:true}" />
			</div>
		</div>
	    <div class="field name required">
			<label class="label" for="Email"><span>Email</span></label>
			<div class="control">
                <input name="email" id="email" title="email" value="<?php echo $customeremail; ?>" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}" />
			</div>
		</div>
		<div class="field name required">
			<label class="label" for="Mobile"><span>Mobile</span></label>
			<div class="control">
				<input name="mobile" id="mobile" title="mobile" value="<?php echo $tel; ?>" type="text" class="input-text" data-validate="{required:true}" />
			</div>
		</div>
		<div class="field name required">
			<label class="label" for="Message"><span>Message</span></label>
			<div class="control">
				<textarea name="message" id="message" title="message" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
			</div>
		</div>
		
<div class="g-recaptcha" data-sitekey="6Lcydz4UAAAAAB2q9_h1j7md79qh6G9sfWRmlkcQ"></div>

	    <?php echo $block->getChildHtml('form.additional.info'); ?>
	</fieldset>
	<div class="actions-toolbar">
	    <div class="primary">
			<input type="hidden" name="hideit" id="hideit" value="" />
			<input type="submit" title="Submit" class="action submit primary" value="Submit">
				
        </div>
    </div>
	
</form>
</div>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 
   var dataForm = $('#custom-form');
   dataForm.mage('validation', {});
 
});
</script>