<div class="container contact-container">
<div class="row">
<div class="col-sm-6 col-xs-12">
<div class="contact-form">
<h2 class="contact-form-title">Keep in touch with us</h2>
<?php echo $block->getLayout()->createBlock('Magento\Contact\Block\ContactForm')->setTemplate('Magento_Contact::form.phtml')->toHtml(); ?>
</div>
</div>
<div class="col-sm-6 col-xs-12">
<h2 class="map-title">Find Us On Map</h2>
<div id="googleMap" style="width: 100%; height: 410px;">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5644.332651157633!2d-84.45832031126399!3d44.98093222317613!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4d3530546b9c9905%3A0xa4c2c00856ddf752!2s10854+M+32+E%2C+Johannesburg%2C+MI+49751%2C+USA!5e0!3m2!1sen!2sin!4v1507895628170" width="100%" height="410" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-6"><img src='<?php echo $this->getViewFileUrl('images/contact-advertise.png'); ?>' ></div>
<div class="col-sm-6 col-xs-12">
<div class="address-box">
<p class="address">10854 M 32 E, Johannesburg,<br /> MI 49751, USA jlas.org</p>
<p class="phone">+1 989-731-4420</p>
<p>Claim this business</p>
<div class="social-icon getsocialize"><ul class="social-footer">
	<h2 class="contact-form-title">Get Socialize :-</h2>
          <li><span>Follow us on : </span></li>
          <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social_icon')->toHtml();?>
        </ul></div>
</div>
</div>
</div>
</div>