 <script type="text/javascript">
   	require(['jquery'],function(jQuery){
        jQuery(document).ready(function(){
	      var value=jQuery("input[name=postcode]").val();
           jQuery.ajax({
            type:'POST',
            url:"<?php echo $block->getUrl('custom/index/reindex/');?>",
            data: {key:value},
            success:function(feedback) {
              // jQuery("#suggestion").html(feedback);
              // jQuery('#loadingmessage').hide();
            },
            error:function(){             
            }    
          });
        });
    });
    </script>