<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct'); 
$blogstr = $product->getBlogs();    
$knowledgebasestr = $product->getKnowledgebase();
$related_products = $product->getRelatedProducts();
$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
$routeName      = $requestInterface->getRouteName();  
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager-> getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA ); 
if(!empty($related_products) && $routeName!='amasty_quickview'){
?>
<div class="alsolike-products">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('relatedproductdetail')->toHtml();

$customerSession = $objectManager->get('Magento\Customer\Model\Session');
   $wishlist_id=array();
  if($customerSession->isLoggedIn()){
    $customerid=$customerSession->getCustomer()->getId();
     $Wishlist_Model = $objectManager->create('\Magento\Wishlist\Controller\WishlistProviderInterface'); 
     $currentUserWishlist = $Wishlist_Model->getWishlist();
    if ($currentUserWishlist) {
      $wishlistItems = $currentUserWishlist->getItemCollection()->getData();
      foreach ($wishlistItems as  $wishlistItems_value) 
      {
         $wishlist_id[]=$wishlistItems_value['product_id'];
      }
    }
  }
?>

        <div id="reletedprod" class="owl-carousel owl-theme">
         
   <?php  foreach ($related_products as $products) {
           $productObject = $objectManager->get('Magento\Catalog\Model\Product');
           $productModel = $productObject->loadByAttribute('sku', $products->getSku());
           $productname=$productModel->getName();
           $producturl=$productModel->getProductUrl();
           $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
           $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $productModel->getImage(); 
           $RatingOb = $objectManager->create('Magento\Review\Model\Rating')->getEntitySummary($products->getId()); ?>

           
            <!--=======item====-->
            <div class="pkg" >
                 <div class="item">
                    <div class="product-box" >
                        <div class="product-image">
                            <a href="#"><img src="<?php echo  $imageUrl; ?>"/></a>
                            <div class="overlay">
                                <div class="overlay-content"><a href="javascript:void(0)"  id='<?php echo $products->getId();?>' class="search-icon"><i class="fa fa-search" ></i></a><a href="<?php echo $producturl; ?>" class="quick-icon"><i class="fa fa-arrow-right" ></i></a></div>
                            </div>
                        </div>
                        <div class="product-details">
                           <a href="<?php echo $producturl; ?>"> <h5><?php echo __($productname); ?></h5> </a>
                            <p class="p-category">Nature’s Baby Organic</p>
                            <p class="p-price">INR <?php echo round($productModel->getPrice()); ?></p>
                            
                        </div>
                    </div>
                </div>
                <span class="cta">
                                <b><a  href="<?php echo $block->getUrl('wishlist',['_secure' => true]); ?>" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>'><?php
                    if ($customerSession->isLoggedIn()) {
                      if (!in_array($products->getId(), $wishlist_id )) { ?>
                    <i class="fa fa-heart-o"><?php }else{ ?> <i class="fa fa-heart"> <?php  } }else{ ?><i class="fa fa-heart-o"><?php } ?></i></a> </b>
                               <!--  <b><i class="fa fa-comment-o"></i> (210) </b> -->
                               <b><a href="<?php  echo $product->getProductUrl(); ?>"><i class="fa fa-comment-o"></i> (<?php
                          if ($RatingOb->getCount()) {
                            echo $RatingOb->getCount();
                           }else{echo '0';}?>)</a>  </b>
                                <?php   $addToCartUrl =  $listBlock->getAddToCartUrl($productModel); ?>
                                                <b><form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
                                               <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit" title="Add to Cart" class="p-product-add">
                                                    <span><i class="fa fa-shopping-cart"></i></span>
                                                </button>
                                    </form></b>
                            </span>
                          </div>
            <!--=======item====-->
                
        

   <?php  } ?>
   </div>
   <script>
      require(['jquery', 'jquery/ui'], function($){
		     $(window).load(function(){
		        $('#reletedprod').owlCarousel({
					loop:true,
					margin:35,
					nav:true,
					mouseDrag: true,
					dots: true,
					responsive:{
						 0:{ items:1 },
						400:{ items:1 },
						600:{ items:2 },
						1000:{ items:4 }
					}
				});
			 });
		  });
   </script>
</div>
<?php } ?>
<?php if($routeName!='amasty_quickview'){ ?>
<div class="prd_detail-blog">
        <div class="blog-list">    
            <?php 
			if($blogstr){
			$blogsarr = explode(',',$blogstr);
			if(count($blogsarr)>0){
			  echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('blogtitleproductdetail')->toHtml();	
			foreach($blogsarr as $postid){
			$postcollection = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Post\Collection')->addFieldToFilter('post_id', $postid);
            foreach($postcollection as $post){
			       $postid=$post->getPostId(); 
                   $commentcollection = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Comment\Collection')->addFieldToFilter('post_id',$postid);
                   $commentcount=count($commentcollection);
                   $likecount=array();
               foreach ($commentcollection as $comment) {
                    $commentid=$comment['comment_id'];
                    $likecModel = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Like\Collection')->addFieldToFilter('comment_id',$commentid);
                    $likecount[]=count($likecModel->getData());
               }
              $likecot=array_sum($likecount);
              $publish_datte=$post->getData()['publish_date'];
              $tempDate = $publish_datte;
              $day = date('l', strtotime($tempDate));// will gives you the week day name 
              $month = date('jS F Y',strtotime($tempDate));?>
              <div class="blog-item">
                <a href="<?php echo $block->getUrl().'blog/post/'.$post->getData()['url_key'] ?>">
                    <div class="blogimage" ><img src="<?php echo $mediaUrl.'mageplaza/blog/post/image'.$post->getData()['image']; ?>"/></div></a>       
                <div class="item-content">
                    <div class="item-title"><a href="<?php echo $block->getUrl().'blog/post/'.$post->getData()['url_key'] ?>"><?php echo $post->getData()['name']; ?></a></div>
                    <div class="item-desc"><?php echo $post->getData()['short_description']; ?></div>
                    <div class="item-bottom">
                    <div class="blog-date"><?php echo $month; ?></div>
                        <div class="blog-status">
                             <div class="blog-like"><?php echo $likecot; ?><i class="fa fa-heart"></i></div>
                        <div class="blog-comment"><?php echo  $commentcount; ?> <i class="fa fa-comments"></i></div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
			<?php } } } } ?>
            <div class="clearfix"></div>
        </div>
</div>
<?php } ?>
<?php
	$storeManager1 =$objectManager->get('Magento\Store\Model\StoreManagerInterface');
	$currentStore  = $storeManager1->getStore();
	$mediaUrl      = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	$nn=$mediaUrl."kb";
    if($knowledgebasestr && $routeName!='amasty_quickview'){
		$knowledgebasearr = explode(',',$knowledgebasestr);
		echo '<div class="knowledgehub-container"> <h2 class="head-title">Knowledge hub goes here...</h2> <p class="head-small">dolor sit amet, consectetur, adipisci velit...</p>';
		if(count($knowledgebasearr)>0){
			echo '<div class="hub-item-coll">';
			foreach($knowledgebasearr as $artid){
				$articles = $objectManager->get('Mirasvit\Kb\Model\ResourceModel\Article\Collection')->addFieldToFilter('article_id', $artid);
				foreach ($articles as  $value) {
					$categories=$value->getCategories();
					$publish_datte  = $value['created_at'];
					$date = new DateTime($publish_datte);
                    $hubdate=$date->format('F d, Y');
					echo '<div class="knowledge-item">';
					     if($value['image']){
					        echo '<div class="knowledge-item-img"><img src="'.$nn.'/'.$value['image'].'" /></div>';
						 }
                         echo '<div class="knowledge-item-cat">'.count($categories).'Mama</div>';						 
					     echo '<div class="knowledge-item-title">'.$value['name'].'</div>';
					     echo '<div class="knowledge-item-details"><div class="hubdate">'.$hubdate.'</div><div class="hubrate"><span><i class="fa fa-heart"></i></span><span>'.$value->getRating().'</span></div></div>';
					echo '</div>';
				}
			}
			echo '</div>';
		}
		echo '</div>';
	}
?>
<script>
 require(['jquery'],function (jQuery) {
    jQuery("#reviewcom").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);
    
});
    jQuery("#ak").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);
     jQuery('.tablabel-1').removeClass("active");
     jQuery('.tablabel-2').removeClass("active");
     jQuery('.tablabel-3').removeClass("active");
     jQuery('.tablabel-0').addClass("active");
	 
	 jQuery('.tabcontent-1').hide();
     jQuery('.tabcontent-2').hide();
     jQuery('.tabcontent-3').hide();
     jQuery('.tabcontent-0').show();

});
jQuery("#reviewcom").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);

     jQuery('.tablabel-1').removeClass("active");
     jQuery('.tablabel-2').removeClass("active");
     jQuery('.tablabel-3').addClass("active");
     jQuery('.tablabel-0').removeClass("active");
	 
	 jQuery('.tabcontent-1').hide();
     jQuery('.tabcontent-2').hide();
     jQuery('.tabcontent-3').show();
     jQuery('.tabcontent-0').hide();
    
});
    
});
</script>

