<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct'); 
$blogstr = $product->getBlogs();    
$knowledgebasestr = $product->getKnowledgebase();
$related_products = $product->getRelatedProducts();
$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
$routeName      = $requestInterface->getRouteName();  
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager-> getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );
$likeblock = $objectManager->create('Nuluv\Liker\Block\Liker');
$currentStore = $storeManager->getStore(); 
$baseUrl = $currentStore->getBaseUrl();
if(!empty($related_products) && $routeName!='amasty_quickview'){
?>
<div class="alsolike-products">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('relatedproductdetail')->toHtml();

$customerSession = $objectManager->get('Magento\Customer\Model\Session');
   $wishlist_id=array();
  if($customerSession->isLoggedIn()){
    $customerid=$customerSession->getCustomer()->getId();
     $Wishlist_Model = $objectManager->create('\Magento\Wishlist\Controller\WishlistProviderInterface'); 
     $currentUserWishlist = $Wishlist_Model->getWishlist();
    if ($currentUserWishlist) {
      $wishlistItems = $currentUserWishlist->getItemCollection()->getData();
      foreach ($wishlistItems as  $wishlistItems_value) 
      {
         $wishlist_id[]=$wishlistItems_value['product_id'];
      }
    }
  }
?>

        <div id="reletedprod" class="owl-carousel owl-theme">
         
   <?php  foreach ($related_products as $products) {
	       $page_type = 1;
           $productObject = $objectManager->get('Magento\Catalog\Model\Product');
           $productModel = $productObject->loadByAttribute('sku', $products->getSku());
           $productname=$productModel->getName();
           $producturl=$productModel->getProductUrl();
           $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
           $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $productModel->getImage(); 
           $RatingOb = $objectManager->create('Magento\Review\Model\Rating')->getEntitySummary($products->getId()); 
		   ?>
            <?php
       $total_likes =$likeblock->getLikeCount($products->getId(),$page_type);
       $client_like_count =$likeblock->isLikeAlredySubmitted($products->getId(),$page_type);
       if($client_like_count){
        $value='Unlike';
        $type_id=0;
        $class='liked';
      }else{
        $value='Like';
        $type_id=1;
        $class='';
      }
      ?>
           
            <!--=======item====-->
            <div class="pkg" >
                 <div class="item">
                    <div class="product-box" >
                        <div class="product-image">
                            <a href="#"><img src="<?php echo  $imageUrl; ?>"/></a>
                            <div class="overlay">
                                <div class="overlay-content"><a href="javascript:void(0)"  id='<?php echo $products->getId();?>' class="search-icon"><i class="fa fa-search" ></i></a><a href="<?php echo $producturl; ?>" class="quick-icon"><i class="fa fa-arrow-right" ></i></a></div>
                            </div>
                        </div>
                        <div class="product-details">
                           <a href="<?php echo $producturl; ?>"> <h5><?php echo __($productname); ?></h5> </a>
                            <p class="p-category">Nature’s Baby Organic</p>
                            <p class="p-price">INR <?php echo round($productModel->getPrice()); ?></p>
                            
                        </div>
                    </div>
                </div>
                <span class="cta">
				<div class="like-action">
		    (<span id="likes_<?php echo $products->getId(); ?>"><?php echo $total_likes; ?></span>)
			<button value="<?php echo  $value;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $products->getId(); ?>" class="like <?php echo $class;?>">
			</button>			
			<img class="like-loader" id="like-loader-<?php echo $products->getId()?>" style="display:none" src="<?php echo $mediaUrl.'loader.gif'?>">
		</div>
                <b>
					<a href="<?php echo $products->getProductUrl(); ?>">
						<i class="fa fa-comment-o"></i> 
						(<span><?php echo ($RatingOb->getCount()) ? $RatingOb->getCount() : '0'; ?></span>)
					</a>
				</b>           
                               
                                <?php   $addToCartUrl =  $listBlock->getAddToCartUrl($productModel); ?>
                                                <b><form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
                                               <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit" title="Add to Cart" class="p-product-add">
                                                    <span><i class="fa fa-shopping-cart"></i></span>
                                                </button>
                                    </form></b>
                            </span>
                          </div>
            <!--=======item====-->
                
        

   <?php  } ?>
   </div>
   <script>
      require(['jquery', 'jquery/ui'], function($){
		     $(window).load(function(){
		        $('#reletedprod').owlCarousel({
					loop:true,
					margin:35,
					nav:true,
					mouseDrag: true,
					dots: true,
					responsive:{
						 0:{ items:1 },
						400:{ items:1 },
						600:{ items:2 },
						1000:{ items:4 }
					}
				});
			 });
		  });
   </script>
</div>
<?php } ?>
<?php if($routeName!='amasty_quickview'){ ?>
<div class="prd_detail-blog">
        <div class="blog-list">    
            <?php 
			if($blogstr){
			$blogsarr = explode(',',$blogstr);
			if(count($blogsarr)>0){
			  echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('blogtitleproductdetail')->toHtml();	
			foreach($blogsarr as $postid){
			$postcollection = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Post\Collection')->addFieldToFilter('post_id', $postid);
            foreach($postcollection as $post){
			       $postid=$post->getPostId(); 
                   $commentcollection = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Comment\Collection')->addFieldToFilter('post_id',$postid);
                   $commentcount=count($commentcollection);
                   $likecount=array();
               foreach ($commentcollection as $comment) {
                    $commentid=$comment['comment_id'];
                    $likecModel = $objectManager->create('Mageplaza\Blog\Model\ResourceModel\Like\Collection')->addFieldToFilter('comment_id',$commentid);
                    $likecount[]=count($likecModel->getData());
               }
              $likecot=array_sum($likecount);
              $publish_datte=$post->getData()['publish_date'];
              $tempDate = $publish_datte;
              $day = date('l', strtotime($tempDate));// will gives you the week day name 
              $month = date('jS F Y',strtotime($tempDate));?>
			  <?php
			  $page_type = 2;
       $total_likes =$likeblock->getLikeCount($post->getPostId(),$page_type);
       $client_like_count =$likeblock->isLikeAlredySubmitted($post->getPostId(),$page_type);
       if($client_like_count){
        $value='Unlike';
        $type_id=0;
        $class='liked';
      }else{
        $value='Like';
        $type_id=1;
        $class='';
      }
	  
      ?>
              <div class="blog-item">
                <a href="<?php echo $block->getUrl().'blog/post/'.$post->getData()['url_key'] ?>">
                    <div class="blogimage" ><img src="<?php echo $mediaUrl.'mageplaza/blog/post/image'.$post->getData()['image']; ?>"/></div></a>       
                <div class="item-content">
                    <div class="item-title"><a href="<?php echo $block->getUrl().'blog/post/'.$post->getData()['url_key'] ?>"><?php echo $post->getData()['name']; ?></a></div>
                    <div class="item-desc"><?php echo $post->getData()['short_description']; ?></div>
                    <div class="item-bottom">
                    <div class="blog-date"><?php echo $month; ?></div>
                        <div class="blog-status">
                             <div class="like-action">
		    (<span id="likes_<?php echo $post->getPostId(); ?>"><?php echo $total_likes; ?></span>)
			<button value="<?php echo  $value;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $post->getPostId(); ?>" class="blike <?php echo $class;?>">
			</button>			
			<img class="like-loader" id="like-loader-<?php echo $post->getPostId(); ?>" style="display:none" src="<?php echo $mediaUrl.'loader.gif'?>">
		</div>
                        <div class="blog-comment"><?php echo  $commentcount; ?> <i class="fa fa-comments"></i></div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
			<?php } } } } ?>
            <div class="clearfix"></div>
        </div>
</div>
<?php } ?>
<?php
    $page_type = 3;
	$storeManager1 =$objectManager->get('Magento\Store\Model\StoreManagerInterface');
	$currentStore  = $storeManager1->getStore();
	$mediaUrl      = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	$nn=$mediaUrl."kb";
	$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
	$connection = $resource->getConnection();
    if($knowledgebasestr && $routeName!='amasty_quickview'){
		$knowledgebasearr = explode(',',$knowledgebasestr);
		echo '<div class="knowledgehub-container"> <h2 class="head-title">Knowledge hub goes here...</h2> <p class="head-small">dolor sit amet, consectetur, adipisci velit...</p>';
		if(count($knowledgebasearr)>0){
			echo '<div class="hub-item-coll">';
			foreach($knowledgebasearr as $artid){
				$articles = $objectManager->create('Mirasvit\Kb\Model\ResourceModel\Article\Collection')
                    ->addFieldToSelect('*')
                    ->addFieldToFilter('article_id', $artid)->load();
				    $total_likes =$likeblock->getLikeCount($artid,$page_type);
					$client_like_count =$likeblock->isLikeAlredySubmitted($artid,$page_type);
					if($client_like_count){
					  $pvalue='Unlike';
					  $type_id=0;
					  $class='liked';
					}else{
					  $pvalue='Like';
					  $type_id=1;
					  $class='';
					}
				foreach ($articles as  $value) {
					$catSql = "SELECT * FROM mst_kb_article_category as cat left join mst_kb_category as ar on cat.ac_category_id=ar.category_id where cat.ac_article_id='".$artid."' ";
				    $allCats = $connection->fetchAll($catSql);
					$cathtml='';
					if(count($allCats)>0){
						foreach($allCats as $category){
							$cathtml.=' <a href="'.$baseUrl.'knowledge-hub/'.$category['url_key'].'.html">'.$category['name'].'</a>';
						}
					}
					$publish_datte  = $value['created_at'];
					$date = new DateTime($publish_datte);
                    $hubdate=$date->format('F d, Y');
					
					echo '<div class="knowledge-item">';
					     if($value['image']){
					        echo '<div class="knowledge-item-img"><a href="'.$value->getUrl().'"><img src="'.$nn.'/'.$value['image'].'" /></a></div>';
						 }
                         echo '<div class="knowledge-item-cat">'.$cathtml.'</div>';						 
					     echo '<div class="knowledge-item-title"><a href="'.$value->getUrl().'">'.$value['name'].'</a></div>';
					     echo '<div class="knowledge-item-details"><div class="hubdate">'.$hubdate.'</div><div class="hubrate">';?>
						<div class="like-action pull-right">
							<button value="<?php echo  $pvalue;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $artid; ?>" class="klike <?php echo $class;?>">
							</button>
                            (<span id="likes_<?php echo $artid; ?>"><?php echo $total_likes; ?></span>)
                             <img class="like-loader" id="like-loader-<?php echo $artid; ?>" style="display:none" src="<?php echo $mediaUrl.'loader.gif'?>">
                        </div>
						 <?php echo '</div></div>';
					echo '</div>';
				}
			}
			echo '</div>';
		}
		echo '</div>';
	}
?>
<script>
 require(['jquery'],function (jQuery) {
    jQuery("#reviewcom").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);
    
});
    jQuery("#ak").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);
     jQuery('.tablabel-1').removeClass("active");
     jQuery('.tablabel-2').removeClass("active");
     jQuery('.tablabel-3').removeClass("active");
     jQuery('.tablabel-0').addClass("active");
	 
	 jQuery('.tabcontent-1').hide();
     jQuery('.tabcontent-2').hide();
     jQuery('.tabcontent-3').hide();
     jQuery('.tabcontent-0').show();

});
jQuery("#reviewcom").click(function() {
    jQuery('html, body').animate({
        scrollTop: jQuery("#custom_scrolls").offset().top
    }, 2000);

     jQuery('.tablabel-1').removeClass("active");
     jQuery('.tablabel-2').removeClass("active");
     jQuery('.tablabel-3').addClass("active");
     jQuery('.tablabel-0').removeClass("active");
	 
	 jQuery('.tabcontent-1').hide();
     jQuery('.tabcontent-2').hide();
     jQuery('.tabcontent-3').show();
     jQuery('.tabcontent-0').hide();
    
});
    
});
</script>
<script type="text/javascript">
require(['jquery'], function(){
	jQuery(document).ready(function(){
		
        jQuery(document).on("click",".blike",function() {
        var id = this.id;   // Getting Button id
        var split_id = id.split("_");
        var text = split_id[0];
        var product_id = split_id[1];  
        jQuery('.prd_detail-blog #like-loader-'+product_id).show();
        jQuery('.prd_detail-blog #'+id).attr("disabled","disabled");

        var type_id= jQuery('.prd_detail-blog #'+id).attr('type-id');
        var page_type= 2;
        // AJAX Request
        jQuery.ajax({
        	url: '<?php echo $block->getUrl("liker/liker/index");?>',
        	type: 'post',
        	data: {type_id:type_id,product_id:product_id,page_type:page_type},
        	dataType: 'json',
        	success: function(data){
        		var likes = data['likes'];
        		jQuery(".prd_detail-blog #likes_"+product_id).text(likes); 
        		if(type_id == 0){
        			jQuery('.prd_detail-blog #'+id).attr('type-id','1');
        			jQuery('.prd_detail-blog #'+id).val('Like');
					jQuery('.prd_detail-blog #'+id).removeClass('liked');
        		}
        		else{
        			jQuery('.prd_detail-blog #'+id).attr('type-id','0');
        			jQuery('.prd_detail-blog #'+id).val('Unlike');
					jQuery('.prd_detail-blog #'+id).addClass('liked');
        		}
                jQuery('.prd_detail-blog #like-loader-'+product_id).hide();
                jQuery('.prd_detail-blog #'+id).removeAttr("disabled");
        	}
        });
    });

    jQuery(document).on("click",".klike",function() {
        var id = this.id;   // Getting Button id
        var split_id = id.split("_");
        var text = split_id[0];
        var product_id = split_id[1];  
        jQuery('.hub-item-coll #like-loader-'+product_id).show();
        jQuery('.hub-item-coll #'+id).attr("disabled","disabled");

        var type_id= jQuery('.hub-item-coll #'+id).attr('type-id');
        var page_type= 3;
        // AJAX Request
        jQuery.ajax({
        	url: '<?php echo $block->getUrl("liker/liker/index");?>',
        	type: 'post',
        	data: {type_id:type_id,product_id:product_id,page_type:page_type},
        	dataType: 'json',
        	success: function(data){
        		var likes = data['likes'];
        		jQuery(".hub-item-coll #likes_"+product_id).text(likes); 
        		if(type_id == 0){
        			jQuery('.hub-item-coll #'+id).attr('type-id','1');
        			jQuery('.hub-item-coll #'+id).val('Like');
					jQuery('.hub-item-coll #'+id).removeClass('liked');
        		}
        		else{
        			jQuery('.hub-item-coll #'+id).attr('type-id','0');
        			jQuery('.hub-item-coll #'+id).val('Unlike');
					jQuery('.hub-item-coll #'+id).addClass('liked');
        		}
                jQuery('.hub-item-coll #like-loader-'+product_id).hide();
                jQuery('.hub-item-coll #'+id).removeAttr("disabled");
        	}
        });
    });


	});

});
</script>
<style>
   .like-action .blike {
    border: none;
    padding: 0;
    background: none;
}
.like-action .blike:hover:before {
    content: "\f004";
    font-family: "FontAwesome";
    color: #7e6674;
}
.like-action .blike:before {
    content: "\f08a";
    font-family: "FontAwesome";
    color: #333;
}
.like-action .klike {
    border: none;
    padding: 0;
    background: none;
}
.like-action .klike:hover:before {
    content: "\f004";
    font-family: "FontAwesome";
    color: #7e6674;
}
.like-action .klike:before {
    content: "\f08a";
    font-family: "FontAwesome";
    color: #333;
}
</style>
