<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass):?>
        <?php $i++; ?>
        <td class="<?php echo /* @noEscape */ $columnClass?><?php /* @noEscape */ echo ($i === $lastItemNumber ? ' last' : '')?>">
		<?php if($i==1){ ?><div id="barcode_<?php echo $_item->getSku(); ?>"></div> <?php } ?>
		<?php /* @escapeNotVerified */ echo $block->getColumnHtml($_item, $columnName) ?>
		<?php 
		  if($i==1){
		  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		  $productId=$_item->getProductId();
		  $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
		  $expiredate=$product->getExpiry_date(); 
		  if($expiredate){
			    $date = new DateTime($expiredate);
				echo '<p><strong>Expiry date: </strong>'.$date->format('F Y').'</p>';
		  }
		  if($product){
			  $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
		      $image_url = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getImage())->resize(100, 100)->getUrl();
		      echo '<img src="'.$image_url.'" /><br>';
		  }?>
		      <input type="text" name="barcode" value="" onkeyup="barcodematching(this.value,'<?php echo $_item->getSku(); ?>')" id="barcodematch" />
		<?php }
		?>
		</td>
    <?php endforeach; ?>
</tr>
