<!-- <div class="kb__search-box hub_search">
	<div class="search-title">Expert advices for parenting and more!</div>
    <form action="<?//= $block->getUrl('kbase/article/s')?>" method="GET" id="kb-s-form">
        <input name='s' id='s' type="text" placeholder="Search..." class="form-control input-text required-entry" required value="<?//= $block->getQuery() ?>">
        <button class="action primary" title="Submit" type="submit">
            <span><i class="fa fa-fw fa-search"></i></span>
        </button>
    </form>
</div> -->