<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
if ($block->getIsEnabled()):
  ?>
  <form id="wio-forum-bookmarks-form" 
        action="<?php echo $block->getActionForm() ?>" 
        method="post"></form>
  <div class="forum-bookmarks-container">
    <?php if ($block->getIsShowAddButton()): ?>
      <button 
        onclick="WIO_FORUM_BOOKMARKS.addBookMark(<?php echo $block->getTopicId() ?>)" 
        class="action secondary" 
        title="<?php echo __('Add to Bookmark') ?>" 
        type="button">
        <span><?php echo __('Add to Bookmark') ?></span>
      </button>
    <?php endif; ?>
    <img src="<?php echo $block->getViewFileUrl('WIO_Forum/images/bookmark.png') ?>" />
    <?php echo __('You have <span id="wio-forum-zero-bookmarks">0</span><a href="javascript:void(0)" onclick="WIO_FORUM_BOOKMARKS.goToBookmarkPage()" id="wio-forum-bookmarks-link"></a> bookmarked items'); ?>
    
  </div>

  <script type="text/javascript">
    WIO_FORUM_BOOKMARKS.showBookmarks();
  </script>
<?php endif; ?>