<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
?>
<div class="main-forum-container">
  <div class="forum-top-block">
    <?php echo $block->getChildHtml('forum.index.top'); ?>
  </div>
  <div class="forum-content-container">
    <?php echo $block->getChildHtml('forum.index.list'); ?>
  <div class="forum-bottom-block">
    <?php echo $block->getChildHtml('forum.index.bottom'); ?>
  </div>
  </div>
</div>