<?php 


///here type-id is 0=>unlike and 1=>like

$total_likes =$block->getLikeCount();
$product_id=$block->getCurrentProduct();
$page_type = $block->getPageType();
$client_like_count =$block->isLikeAlredySubmitted();
if($client_like_count){
	$value='Unlike';
	$type_id=0;
}else{
$value='Like';
	$type_id=1;
}

?>
<div class="post">

	<div class="post-action">

		<input type="button" value="<?php echo  $value;?>" type-id="<?php echo $type_id ?>" page-type="<?php echo $page_type;?>" id="like_<?php echo $product_id; ?>" class="like" />&nbsp;(<span id="likes_<?php echo $product_id; ?>"><?php echo $total_likes; ?></span>)&nbsp;</div>
</div>


