
<script type="text/javascript">
require(['jquery'], function(){
	jQuery(document).ready(function(){
		
        jQuery(document).on("click",".like",function() {
        var id = this.id;   // Getting Button id
        var split_id = id.split("_");

        
        

        var text = split_id[0];
        var product_id = split_id[1];  
        jQuery('#like-loader-'+product_id).show();
        jQuery('#'+id).attr("disabled","disabled");

        var type_id= jQuery('#'+id).attr('type-id');
        var page_type= jQuery('#'+id).attr('page-type');

        
        // AJAX Request
        jQuery.ajax({
        	url: '<?php echo $block->getUrl("liker/liker/index");?>',
        	type: 'post',
        	data: {type_id:type_id,product_id:product_id,page_type:page_type},
        	dataType: 'json',
        	success: function(data){
        		var likes = data['likes'];
        		jQuery(".page-wrapper #likes_"+product_id).text(likes); 
        		if(type_id == 0){
        			jQuery('.page-wrapper #'+id).attr('type-id','1');
        			jQuery('.page-wrapper #'+id).val('Like');
					jQuery('.page-wrapper #'+id).removeClass('liked');
        		}
        		else{
        			jQuery('.page-wrapper #'+id).attr('type-id','0');
        			jQuery('.page-wrapper #'+id).val('Unlike');
					jQuery('.page-wrapper #'+id).addClass('liked');
        		}
                jQuery('.page-wrapper #like-loader-'+product_id).hide();
                jQuery('.page-wrapper #'+id).removeAttr("disabled");
        	}
        });
    });




	});

});
</script>