<?php
/**
 * webideaonline.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://webideaonline.com/licensing/
 *
 */
?>
<div class="forum-util forum-util-bottom clearfix">
  <?php echo $block->getChildHtml('forum.ui.jumpto.bottom'); ?>
  <div class="clearfix"></div>
  <?php echo $block->getChildHtml('forum.ui.statistic.bottom'); ?>
  <div class="clearfix"></div>
  <?php echo $block->getChildHtml('forum.ui.whoisonline.bottom'); ?>
</div>