<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="prd_dealer" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span class="stock_status instock"><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
            <?php echo __('Sold by ');?><?php $brandname= $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getProductBrand(), 'product_brand'); 
               $getAttribute=explode(',', $brandname);
               foreach ($getAttribute as $getAttributes) {
                   
    
$attr = $_product->getResource()->getAttribute('product_brand');
 if ($attr->usesSource()) {?>
 <strong><?php echo $optionText = $attr->getSource()->getOptionText($getAttributes);?></strong><?php
 }
}
    
            ?><?php echo __(' and Fulfilled by <strong>Nuluv</strong>.'); ?>
        </div>
    <?php else: ?>
        <div class="prd_dealer" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span class="stock_status outstock"><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
            <?php echo __('Sold by ');?><?php $brandname= $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getProductBrand(), 'product_brand'); 
               $getAttribute=explode(',', $brandname);
               foreach ($getAttribute as $getAttributes) {
                   
    
$attr = $_product->getResource()->getAttribute('product_brand');
 if ($attr->usesSource()) {?>
 <strong><?php echo $optionText = $attr->getSource()->getOptionText($getAttributes);?></strong><?php
 }
}
    
            ?><?php echo __(' and Fulfilled by <strong>Nuluv</strong>.'); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<style type="text/css">
	.stock_status.outstock {
    background: #af2c2c;
    margin-right: 5px;
}
</style>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $crossSellProducts = $_product->getCrossSellProducts(); 
      if (!empty($crossSellProducts)) {
		echo '<select name="crosssell" onchange="crosssell(this.value);">';
		echo '<option>Please select varient</option>';
		foreach ($crossSellProducts as $crossSellProduct) {
			$product = $objectManager->create('Magento\Catalog\Model\Product')->load($crossSellProduct->getId());
			$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
			echo '<option value="'.$crossSellProduct->getProductUrl().'">'.$product->getName().' - '.$priceHelper->currency($product->getFinalPrice(), true, false).'</option>';       
		}
		echo '</select>';
	}
?>
<script>
   function crosssell(purl){
	   window.location= purl;
   }
</script>