<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
 <?php 
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $_product = $block->getProduct(); 

        $customerSession = $objectManager->get('Magento\Customer\Model\Session');
        $wishlist_id=array();
        if($customerSession->isLoggedIn()){
        $customerid=$customerSession->getCustomer()->getId();
        $Wishlist_Model = $objectManager->create('\Magento\Wishlist\Controller\WishlistProviderInterface'); 
        $currentUserWishlist = $Wishlist_Model->getWishlist();
        if ($currentUserWishlist) {
          $wishlistItems = $currentUserWishlist->getItemCollection()->getData();
          foreach ($wishlistItems as  $wishlistItems_value) 
          {
             $wishlist_id[]=$wishlistItems_value['product_id'];
          }
        }
    // echo "<pre>";
    // print_r($wishlist_id);
    // echo "</pre>";
   
  }
 ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset prd_control">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>


        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
            <?php $RatingOb = $objectManager->create('Magento\Review\Model\Rating')->getEntitySummary($_product->getId());?>
       <?php echo $this->getLayout()->createBlock("Nuluv\Liker\Block\Liker")->setTemplate("Nuluv_Liker::likes.phtml")->toHtml();?>
        <div class="like_count"><a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span>
         <?php
                    if ($customerSession->isLoggedIn()) {
                      if (!in_array($_product->getId(), $wishlist_id )) { ?>
                    <i class="fa fa-heart-o"><?php }else{ ?> <i class="fa fa-heart"> <?php  } }else{ ?><i class="fa fa-heart-o"><?php } ?></i></span></a></div>
         <div class="comment_count" id="reviewcom"><a href="#" ?><i class="fa fa-comment-o"></i></a> (<?php
                          if ($RatingOb->getCount()) {
                            echo $RatingOb->getCount();
                           }else{echo '0';}?>)</div>
        </div>
        
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php //if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php //endif; ?>



