<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$countt = count($_product->getMediaGalleryImages());
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$customeremail='';
if ($customerSession->isLoggedIn()) {
	$customeremail=$customerSession->getCustomer()->getEmail();
}
?>
<?php if(!$_product->issaleable()){ ?>
<div class="block newsletter stocknotification">
    <div class="title">
        <strong>
            <?php
            echo $block->escapeHtml(
                __(
                    'Product is unavailable. Would you like to get e-mail '
                    . 'notification when the product will be back in stock?'
                )
            );
            ?>
        </strong>
    </div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php echo $storeManager->getStore()->getBaseUrl().'stocknotification/index/signup/product_id/'.$_product->getId(); ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="stocknotification-validate-email">
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email" id="email"
                       value="<?php echo $customeremail; ?>"
                       placeholder="<?php echo __('Enter your e-mail') ?>"
                       data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary">
                    <?php echo __('Notify Me') ?>
                </button>
            </div>
        </form>
    </div>
</div>
<?php } ?>
<div class="peta_logo">
 <?php if($_product->getBrandimages()){
		 echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getBrandimages(), 'brandimages');
	} ?>
<?php /* echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('detaillogo')->toHtml(); */ ?>
<div class="clearfix"></div>
</div>
<?php if($_product->getShortDescription()){ ?>
<div class="sdsds prd_overview <?php /* @escapeNotVerified */ echo $_className?>">
	<strong>Quick Overview :</strong>
	<div class="short-description-cls">
    <?php /* @escapeNotVerified */ echo substr($_product->getShortDescription(), 0, 200); ?>
    <div  style="text-align: right;"><a id="ak" href="#">More Info...</a></div>
	</div>
</div>
<?php } ?>
<div class="share"><?php echo $block->getLayout()->createBlock('Magebuzz\Socialshare\Block\Socialshare')->setTemplate('Magebuzz_Socialshare::socialshare.phtml')->toHtml(); ?></div>


