<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$blogstr = $product->getBlogs();    
$knowledgebasestr = $product->getKnowledgebase();    
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    $categoryname[]= $cat->getName();
    }

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager-> getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );

/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */

/** Apply filters here */



?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed" id="custom_scrolls">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $i=0; foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title tablabel-<?php echo $i;?>"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
					   
						<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
							$storeManager =    $objectManager->create('\Magento\Store\Model\StoreManagerInterface');		
							$storeId = $storeManager->getStore()->getId();
							$reviewFactory->getEntitySummary($product, $storeId);

							$reviewCount = $ratingSummary = $product->getRatingSummary()->getRatingSummary();
						?>

                        <?php /* @escapeNotVerified */ 
						
							if($label!='Comments'){
								echo $label;
							}
							if($label=='Comments'){
								if($reviewCount!=''){
									echo $label;
								}
							}
						?>
                    </a>
                </div>
                <div class="data item content tabcontent-<?php echo $i;?>" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php $i++; endforeach; ?>
        </div>
    </div>
<?php endif; ?>