<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php $_product = $block->getProduct() ?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseurl=$store->getBaseUrl();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$prodCatids=$_product->getCategoryIds();
$caturl='';
if(count($prodCatids)>0){
	$categoryId=$prodCatids[0];
	$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $catname = $cat->getName();
	$caturl=$cat->getUrlKey();
}
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$action_name = $request->getActionName();
$module_name = $request->getModuleName();
$controller_name = $request->getControllerName();
?>
<h3 class="prd_title"><?php echo $block->getProduct()->getData('name'); ?></h3>
    <h6 class="prd_type rev"><?php $brandname= $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getProductBrand(), 'product_brand'); 
               $getAttribute=explode(',', $brandname);
               foreach ($getAttribute as $getAttributes) {
				 $attr = $_product->getResource()->getAttribute('product_brand');
				 /*echo '<pre>';
				 print_r($attr->getSource());
				 echo '<pre>';*/
				 if ($attr->usesSource()) {
					 $bname = ltrim($attr->getSource()->getOptionText($getAttributes));
					 $bname=strtolower($bname);
					 $finalbrandurl=urlencode(preg_replace('/\-{1,}/', '', preg_replace('/\s{1,}/', '', $bname)));
					 echo '<a href="'.$baseurl.$caturl.'/'.$finalbrandurl.'.html">'.$attr->getSource()->getOptionText($getAttributes).'</a>';
				 } 
			   } 
			 ?>
			 </h6>
<!--<div id="reviewdiv"><?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?></div>-->