<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_ProductStockAlert
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/* @var $block \Bss\ProductStockAlert\Block\Product\View */
?>
<div id="product_stock_alert_container"></div>
<script type="text/x-magento-init">
    {
        "#product_stock_alert_container": {
            "productStockalertAjax": {
                "url" : "<?php /* @escapeNotVerified */ echo $block->getAjaxUrl(); ?>",
                "action" : "<?php /* @escapeNotVerified */ echo $block->getPostAction(); ?>",
                "productId" : "<?php /* @escapeNotVerified */ echo $block->getProductId(); ?>",
                "statusAvailable" : "<?php /* @escapeNotVerified */ echo $block->getStatusAvailable(); ?>"
            }
        }
    }
</script>
