<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<style type="text/css">
    .abs-shopping-cart-items-desktop, .block-cart-failed, .cart-container .form-cart, .cart-container .cart-gift-item{
        /*width: 100% !important;*/
    }
 .action.primary{
     	background: #7e6674;
    	border: 1px solid #7e6674
     	
    }
    .action.primary:focus{
    	background: #7e6674;
    	border: 1px solid #7e6674
    }
     .action.primary:active{
     	background: #7e6674;
    	border: 1px solid #7e6674
     	
    }
     .action.primary:hover{
     	background: #ebebeb;
     	color: #333;
    	border: 1px solid #7e6674
     	
    }
    button, .cart.table-wrapper .actions-toolbar>.action, .cart.table-wrapper .action-gift{
    	background: #7e6674;
    	color: #fff;
    	border: 1px solid #7e6674

    }
    .cart-summary>.title{
      display: none;
    }
    #block-shipping{
      display: none;
    }
    .cart-summary .block{
      text-align: left;
    }
    .price-excluding-tax.pric {
    padding-top: 6px;
   }

</style>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif; ?>
        <table id="shopping-cart-table"
               class="cart items data table table table-bordered cart-table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
                <tr><th style="width:5%" >S.No</th>
                    <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Image') ?></span></th>
                    <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
                    <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span>
                    </th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Total') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Remove') ?></span></th>
                </tr>
            </thead>
            <tbody>
      
        
            <?php $i=1;
             foreach ($block->getItems() as $_item): ?>
             <tr>
             <td><?php echo $i; ?></td>
                <?php echo $block->getItemHtml($_item) ?>
                </tr>
            <?php $i++;
            endforeach ?>
             
    </tbody>
        </table>
        
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

<script>
function updatebuttonvalidate(){
require(['jquery'],function (jquery) {
    jQuery(document).ready(function(){
            /*document.getElementById('continueShopping').disabled = true;*/
             jquery('#continueShopping').click(function () {
            //DO SOMETHING
            return true;
               });
            document.getElementById('empty_cart_button').disabled = false;
            document.getElementById('cartproceedtocheckout').disabled = false;
        
        });
});
}
</script>
